/* prjParams.h - dynamically generated configuration header */


/*
GENERATED: Sun Apr 17 13:56:08 +0300 2022
DO NOT EDIT - file is regenerated whenever the project changes
*/

#ifndef INCprjParamsh
#define INCprjParamsh


/*** INCLUDED COMPONENTS ***/

#define DRV_BUS_FDT_ROOT
#define DRV_BUS_FDT_SIMPLE
#define DRV_INT_VXSIM
#define DRV_NET_VXSIM
#define DRV_NEXUS_GENERIC
#define DRV_SIO_VXSIM
#define DRV_TIMER_VXSIM
#define INCLUDE_ADR_SPACE_DIRECT_MAP
#define INCLUDE_ADR_SPACE_LIB
#define INCLUDE_ADR_SPACE_LIB_ARCH
#define INCLUDE_ADR_SPACE_SHELL_CMD
#define INCLUDE_ADR_SPACE_SHOW
#define INCLUDE_ANALYSIS_AGENT
#define INCLUDE_ANALYSIS_AUX_CLOCK
#define INCLUDE_ANALYSIS_DEBUG_SUPPORT
#define INCLUDE_ANALYSIS_SCRIPT
#define INCLUDE_ANSI_ASSERT
#define INCLUDE_ANSI_COMPLEX
#define INCLUDE_ANSI_CTYPE
#define INCLUDE_ANSI_ERRNO
#define INCLUDE_ANSI_FENV
#define INCLUDE_ANSI_FLOAT
#define INCLUDE_ANSI_INTTYPES
#define INCLUDE_ANSI_ISO646
#define INCLUDE_ANSI_LIMITS
#define INCLUDE_ANSI_LOCALE
#define INCLUDE_ANSI_MATH
#define INCLUDE_ANSI_SETJMP
#define INCLUDE_ANSI_SIGNAL
#define INCLUDE_ANSI_STDALIGN
#define INCLUDE_ANSI_STDARG
#define INCLUDE_ANSI_STDATOMIC
#define INCLUDE_ANSI_STDBOOL
#define INCLUDE_ANSI_STDDEF
#define INCLUDE_ANSI_STDINT
#define INCLUDE_ANSI_STDIO
#define INCLUDE_ANSI_STDLIB
#define INCLUDE_ANSI_STDNORETURN
#define INCLUDE_ANSI_STRING
#define INCLUDE_ANSI_TGMATH
#define INCLUDE_ANSI_THREADS
#define INCLUDE_ANSI_TIME
#define INCLUDE_ANSI_UCHAR
#define INCLUDE_ANSI_WCHAR
#define INCLUDE_ANSI_WCTYPE
#define INCLUDE_APPL_LOG_UTIL
#define INCLUDE_ARPAINETLIB
#define INCLUDE_ATOMIC_OPERATORS
#define INCLUDE_AUX_CLK
#define INCLUDE_AVL_TREES
#define INCLUDE_AVL_UINT_TREES
#define INCLUDE_BALANCE_PRIORITY
#define INCLUDE_BANNER
#define INCLUDE_BASE_KERNEL
#define INCLUDE_BLIB
#define INCLUDE_BMPLIB
#define INCLUDE_BOARD_INIT
#define INCLUDE_BOARD_LIB_INIT
#define INCLUDE_BOOT_LINE_INIT
#define INCLUDE_BSD_STRINGS
#define INCLUDE_BSP_MACROS
#define INCLUDE_CACHE_ENABLE
#define INCLUDE_CACHE_SUPPORT
#define INCLUDE_CAFE_EP_AGGREGATOR
#define INCLUDE_CAFE_EP_AUX_CLOCK
#define INCLUDE_CAFE_EP_CAFE_NAMESPACE
#define INCLUDE_CAFE_EP_ELOG
#define INCLUDE_CAFE_EP_PERFORMANCE_PROFILER
#define INCLUDE_CAFE_EP_PRINT
#define INCLUDE_CAFE_EP_REALTIME
#define INCLUDE_CAFE_EP_STREAM_READER
#define INCLUDE_CAFE_EP_STREAM_WRITER
#define INCLUDE_CAFE_EP_SYSINFO
#define INCLUDE_CAFE_EP_SYS_CLOCK
#define INCLUDE_CAFE_EP_TCF_UPLOAD
#define INCLUDE_CAFE_EP_TIMER
#define INCLUDE_CAFE_EP_TIMESTAMP_NORMALIZER
#define INCLUDE_CAFE_EP_VXWORKS
#define INCLUDE_CAFE_EP_VXWORKS_POLLING
#define INCLUDE_CAFE_PRINT
#define INCLUDE_CAFE_RTP
#define INCLUDE_CAFE_TCF_SERVICE
#define INCLUDE_CAFE_VX_TIMESTAMP
#define INCLUDE_CHECKSUM
#define INCLUDE_CLASS_LIB
#define INCLUDE_CLASS_LIST
#define INCLUDE_CLASS_SHOW
#define INCLUDE_CONDVAR
#define INCLUDE_CONDVAR_OPEN
#define INCLUDE_CONDVAR_SHOW
#define INCLUDE_COPROCESSOR
#define INCLUDE_COPROCESSOR_SHOW
#define INCLUDE_CPC
#define INCLUDE_CPLUS
#define INCLUDE_CPLUS_DEMANGLER
#define INCLUDE_CPLUS_LANG
#define INCLUDE_CPLUS_STDLIB
#define INCLUDE_CTORS_DTORS
#define INCLUDE_C_STDLIB
#define INCLUDE_DATACOLLECTOR
#define INCLUDE_DATACOLLECTOR_SHOW
#define INCLUDE_DATA_NO_EXEC
#define INCLUDE_DEBUG
#define INCLUDE_DEBUG_AGENT
#define INCLUDE_DEBUG_AGENT_BANNER
#define INCLUDE_DEBUG_AGENT_HOSTFS
#define INCLUDE_DEBUG_AGENT_START
#define INCLUDE_DEBUG_AGENT_VX7
#define INCLUDE_DEBUG_SHELL_CMD
#define INCLUDE_DEVICE_MANAGER
#define INCLUDE_DISK_UTIL
#define INCLUDE_DISK_UTIL_SHELL_CMD
#define INCLUDE_DLL
#define INCLUDE_DOSFS
#define INCLUDE_DOSFS_CACHE
#define INCLUDE_DOSFS_CHKDSK
#define INCLUDE_DOSFS_DIR_FIXED
#define INCLUDE_DOSFS_DIR_VFAT
#define INCLUDE_DOSFS_FAT
#define INCLUDE_DOSFS_FMT
#define INCLUDE_DOSFS_MAIN
#define INCLUDE_DOSFS_SHOW
#define INCLUDE_DOSFS_VOL_BIO_BUFFER_SIZE
#define INCLUDE_EDR_DEFAULT_POLICY
#define INCLUDE_EDR_ERRLOG
#define INCLUDE_EDR_PM
#define INCLUDE_EDR_POLICY_HOOKS
#define INCLUDE_EDR_SHELL_CMD
#define INCLUDE_EDR_SHOW
#define INCLUDE_EDR_STUB
#define INCLUDE_EDR_SYSDBG_FLAG
#define INCLUDE_END
#define INCLUDE_END_COMMON
#define INCLUDE_END_ETHER_HDR
#define INCLUDE_ENV_VARS
#define INCLUDE_ERF
#define INCLUDE_ERF_TASK_OPTION
#define INCLUDE_ETHERNET
#define INCLUDE_EVENTPOINT
#define INCLUDE_EVENTPOINT_STUB
#define INCLUDE_EXC_HANDLING
#define INCLUDE_EXC_SHOW
#define INCLUDE_EXC_SIGNALS
#define INCLUDE_EXC_TASK
#define INCLUDE_FDT_LIB
#define INCLUDE_FDT_SHOW
#define INCLUDE_FORMATTED_IO
#define INCLUDE_FS_EVENT_UTIL
#define INCLUDE_FS_MONITOR
#define INCLUDE_FTP
#define INCLUDE_GETADDRINFO_SYSCTL
#define INCLUDE_GETOPT
#define INCLUDE_GETSERVBYNAME
#define INCLUDE_GETSERVBYPORT
#define INCLUDE_HANDLE_SHOW
#define INCLUDE_HASH
#define INCLUDE_HOOKS
#define INCLUDE_HOOK_SHOW
#define INCLUDE_HOSTNAME_SYSCTL
#define INCLUDE_HOST_TBL
#define INCLUDE_HOST_TBL_SYSCTL
#define INCLUDE_HW_FP
#define INCLUDE_HW_FP_MREGS
#define INCLUDE_HW_FP_SHOW
#define INCLUDE_IDLE_TASKS
#define INCLUDE_INETLIB
#define INCLUDE_INTERRUPT_ENTROPY_ADD
#define INCLUDE_INT_LIB_INIT
#define INCLUDE_IO_BASIC
#define INCLUDE_IO_FILE_SYSTEM
#define INCLUDE_IO_FILE_SYSTEM_BASIC
#define INCLUDE_IO_MISC
#define INCLUDE_IO_POSIX
#define INCLUDE_IO_REMOVABLE
#define INCLUDE_IO_SYSTEM
#define INCLUDE_IPATTACH
#define INCLUDE_IPCOM
#define INCLUDE_IPCOM_USE_ETHERNET
#define INCLUDE_IPCOM_USE_INET
#define INCLUDE_IPCOM_USE_INET6
#define INCLUDE_IPCOM_USR
#define INCLUDE_IPNET
#define INCLUDE_IPNET6_USE_MCAST_ROUTING
#define INCLUDE_IPNET_IFCONFIG_1
#define INCLUDE_IPNET_LOOPBACK_CONFIG
#define INCLUDE_IPNET_SOCKET
#define INCLUDE_IPNET_SYSCTL
#define INCLUDE_IPNET_USE_LOOPBACK
#define INCLUDE_IPNET_USE_MCAST_ROUTING
#define INCLUDE_IPNET_USE_NETLINKSOCK
#define INCLUDE_IPNET_USE_ROUTESOCK
#define INCLUDE_IPNET_USE_SOCK_COMPAT
#define INCLUDE_IPNET_USE_VLAN
#define INCLUDE_IPRADVD
#define INCLUDE_IPTCP
#define INCLUDE_IPV4
#define INCLUDE_IPV6
#define INCLUDE_IPWRAP_GETADDRINFO
#define INCLUDE_IPWRAP_GETIFADDRS
#define INCLUDE_IPWRAP_IFCONFIG
#define INCLUDE_IPWRAP_INETLIB
#define INCLUDE_IPWRAP_IPPROTO
#define INCLUDE_ISR_DEFER
#define INCLUDE_ISR_HANDLER_INIT
#define INCLUDE_ISR_OBJECTS
#define INCLUDE_ISR_SHOW
#define INCLUDE_JOB_DEFER
#define INCLUDE_JOB_QUEUE
#define INCLUDE_JOB_TASK
#define INCLUDE_KERNEL
#define INCLUDE_KERNEL_ARCH
#define INCLUDE_KERNEL_COMMON_HEAP
#define INCLUDE_KERNEL_HARDENING
#define INCLUDE_KERNEL_PROXIMITY_HEAP
#define INCLUDE_KERNEL_STDSTREAM
#define INCLUDE_LINKBUFPOOL
#define INCLUDE_LLVM_INTRINSICS
#define INCLUDE_LLVM_INTRINSICS_ARCH
#define INCLUDE_LOADER
#define INCLUDE_LOADER_CODE
#define INCLUDE_LOADER_HOOKS
#define INCLUDE_LOGGING
#define INCLUDE_LSTLIB
#define INCLUDE_MAPPED_FILES_SHOW
#define INCLUDE_MAPPED_FILES_SHOW_SHELL_CMD
#define INCLUDE_MBUF_UTIL1
#define INCLUDE_MEMORY_CONFIG
#define INCLUDE_MEM_MGR_BASIC
#define INCLUDE_MEM_MGR_FULL
#define INCLUDE_MEM_MGR_INFO
#define INCLUDE_MEM_RTP
#define INCLUDE_MEM_SHOW
#define INCLUDE_MIB2_IF
#define INCLUDE_MMAP
#define INCLUDE_MMU_BASIC
#define INCLUDE_MMU_GLOBAL_MAP
#define INCLUDE_MODULE_MANAGER
#define INCLUDE_MODULE_SHELL_CMD
#define INCLUDE_MSG_Q
#define INCLUDE_MSG_Q_CREATE_DELETE
#define INCLUDE_MSG_Q_EVENTS
#define INCLUDE_MSG_Q_INFO
#define INCLUDE_MSG_Q_OPEN
#define INCLUDE_MSG_Q_SHOW
#define INCLUDE_MUX
#define INCLUDE_MUX2
#define INCLUDE_MUX2_OVER_END
#define INCLUDE_MUX_COMMON
#define INCLUDE_NETBUFLIB
#define INCLUDE_NETBUFPOOL
#define INCLUDE_NETMASK_GET
#define INCLUDE_NETWORK
#define INCLUDE_NET_BOOT
#define INCLUDE_NET_DAEMON
#define INCLUDE_NET_DRV
#define INCLUDE_NET_HOST_SETUP
#define INCLUDE_NET_IOCTL_SC
#define INCLUDE_NET_REM_IO
#define INCLUDE_NET_SYSCTL
#define INCLUDE_NV_RAM
#define INCLUDE_OBJECT_SHOW
#define INCLUDE_OBJ_INFO
#define INCLUDE_OBJ_LIB
#define INCLUDE_OBJ_OPEN
#define INCLUDE_OBJ_OWNERSHIP
#define INCLUDE_OFFSET_SYMBOLS
#define INCLUDE_PASSFS
#define INCLUDE_PASSFS_SYM_TBL
#define INCLUDE_PATHNAME_RESOLUTION_STRICT
#define INCLUDE_PG_MGR_BASIC
#define INCLUDE_PG_MGR_LIB
#define INCLUDE_PG_MGR_SHOW
#define INCLUDE_PG_POOL_LIB
#define INCLUDE_PG_POOL_PHYS_LIB
#define INCLUDE_PG_POOL_SHOW
#define INCLUDE_PG_POOL_VIRT_LIB
#define INCLUDE_PIPES
#define INCLUDE_PMAP_LIB
#define INCLUDE_POOL
#define INCLUDE_POOL_SHOW
#define INCLUDE_POSIX_AIO
#define INCLUDE_POSIX_AIO_SHOW
#define INCLUDE_POSIX_AIO_SYSDRV
#define INCLUDE_POSIX_CLOCKS
#define INCLUDE_POSIX_DIRLIB
#define INCLUDE_POSIX_FS
#define INCLUDE_POSIX_FTRUNC
#define INCLUDE_POSIX_MAPPED_FILES
#define INCLUDE_POSIX_MEM
#define INCLUDE_POSIX_MQ
#define INCLUDE_POSIX_MQ_SHOW
#define INCLUDE_POSIX_PTHREADS
#define INCLUDE_POSIX_SCHED
#define INCLUDE_POSIX_SEM
#define INCLUDE_POSIX_SEM_SHOW
#define INCLUDE_POSIX_SIGNALS
#define INCLUDE_POSIX_SYMLINK
#define INCLUDE_POSIX_TIMERS
#define INCLUDE_POSIX_TIMER_SHOW
#define INCLUDE_POSIX_UMASK
#define INCLUDE_POSIX_USER_GROUP
#define INCLUDE_PROTECT_INTERRUPT_STACK
#define INCLUDE_PROTECT_INTERRUPT_STACK_NON_CORE0
#define INCLUDE_PROTECT_TASK_STACK
#define INCLUDE_PROTECT_TEXT
#define INCLUDE_PROTECT_VEC_TABLE
#define INCLUDE_PTYDRV
#define INCLUDE_Q_FIFO
#define INCLUDE_Q_PRI_BMAP
#define INCLUDE_Q_PRI_DELTA
#define INCLUDE_Q_PRI_LIST
#define INCLUDE_RAM_DISK
#define INCLUDE_RAM_DISK_FORMAT_ANY
#define INCLUDE_RANDOM_NUM_GEN
#define INCLUDE_RAWFS
#define INCLUDE_RBUFF
#define INCLUDE_RBUFF_SHOW
#define INCLUDE_REBOOT_HOOKS
#define INCLUDE_REMLIB
#define INCLUDE_REMLIB_SYSCTL
#define INCLUDE_RNG_BUF
#define INCLUDE_ROMFS
#define INCLUDE_ROMFS_DRV
#define INCLUDE_RTP
#define INCLUDE_RTP_APPL_INIT_BOOTLINE
#define INCLUDE_RTP_APPL_USER
#define INCLUDE_RTP_ARCH
#define INCLUDE_RTP_DEBUG
#define INCLUDE_RTP_DEBUG_COMMAND
#define INCLUDE_RTP_HOOKS
#define INCLUDE_RTP_IO_MISC
#define INCLUDE_RTP_LIMITS
#define INCLUDE_RTP_SHELL_C
#define INCLUDE_RTP_SHELL_CMD
#define INCLUDE_RTP_SHOW
#define INCLUDE_RTP_SHOW_SHELL_CMD
#define INCLUDE_RTP_SIGNALS
#define INCLUDE_RTP_SYMBOL_TABLE
#define INCLUDE_SC_CONDVAR
#define INCLUDE_SC_ENV_ACCESS
#define INCLUDE_SC_IOS
#define INCLUDE_SC_KERNEL
#define INCLUDE_SC_MMAN
#define INCLUDE_SC_PIPE
#define INCLUDE_SC_POSIX
#define INCLUDE_SC_RTP_LIMITS
#define INCLUDE_SC_SD
#define INCLUDE_SC_SEM_EXCHANGE
#define INCLUDE_SC_SEM_READ_WRITE
#define INCLUDE_SC_SHL
#define INCLUDE_SC_SOCKLIB
#define INCLUDE_SC_SYSCTL
#define INCLUDE_SEC_HASH_MD5
#define INCLUDE_SEC_HASH_MD5_OPENSSL
#define INCLUDE_SEC_HASH_SHA1
#define INCLUDE_SEC_HASH_SHA1_OPENSSL
#define INCLUDE_SEC_HASH_SHA256
#define INCLUDE_SEC_HASH_SHA256_OPENSSL
#define INCLUDE_SELECT
#define INCLUDE_SELECT_SUPPORT
#define INCLUDE_SEM_BINARY
#define INCLUDE_SEM_BINARY_CREATE
#define INCLUDE_SEM_COUNTING
#define INCLUDE_SEM_COUNTING_CREATE
#define INCLUDE_SEM_DELETE
#define INCLUDE_SEM_EVENTS
#define INCLUDE_SEM_EXCHANGE
#define INCLUDE_SEM_INFO
#define INCLUDE_SEM_LIB
#define INCLUDE_SEM_MUTEX
#define INCLUDE_SEM_MUTEX_CREATE
#define INCLUDE_SEM_OPEN
#define INCLUDE_SEM_READ_WRITE
#define INCLUDE_SEM_READ_WRITE_CREATE
#define INCLUDE_SEM_SHOW
#define INCLUDE_SHARED_DATA
#define INCLUDE_SHARED_DATA_SHOW
#define INCLUDE_SHARED_DATA_SHOW_SHELL_CMD
#define INCLUDE_SHELL
#define INCLUDE_SHELL_BANNER
#define INCLUDE_SHELL_CORE
#define INCLUDE_SHELL_EMACS_MODE
#define INCLUDE_SHELL_INTERP_C
#define INCLUDE_SHELL_INTERP_CMD
#define INCLUDE_SHELL_VI_MODE
#define INCLUDE_SHL
#define INCLUDE_SHL_SHELL_CMD
#define INCLUDE_SHL_SHOW
#define INCLUDE_SHOW_ROUTINES
#define INCLUDE_SIGEVENT
#define INCLUDE_SIGNALS
#define INCLUDE_SIGNAL_ARCH
#define INCLUDE_SIO
#define INCLUDE_SLL
#define INCLUDE_SMP_DEMO
#define INCLUDE_SMP_INIT
#define INCLUDE_SMP_SCHED_DEFAULT_POLICY
#define INCLUDE_SOCKLIB
#define INCLUDE_SPINLOCK
#define INCLUDE_SPINLOCK_ISR_ND
#define INCLUDE_SPY
#define INCLUDE_SPY_SHELL_CMD
#define INCLUDE_STACKTRACE
#define INCLUDE_STACKTRACE_MODULE
#define INCLUDE_STACKTRACE_SHD
#define INCLUDE_STARTUP_SCRIPT
#define INCLUDE_STAT_SYM_TBL
#define INCLUDE_STDIO_SHOW
#define INCLUDE_STOP_MODE_AGENT
#define INCLUDE_STOP_MODE_AGENT_BANNER
#define INCLUDE_STOP_MODE_AGENT_END
#define INCLUDE_STOP_MODE_AGENT_START
#define INCLUDE_SV_DATACOLLECTOR
#define INCLUDE_SW_RANDOM_NUM_GEN
#define INCLUDE_SYM_SHELL_CMD
#define INCLUDE_SYM_TBL
#define INCLUDE_SYM_TBL_INIT
#define INCLUDE_SYM_TBL_SHOW
#define INCLUDE_SYSCALL_HOOKS
#define INCLUDE_SYSCLK_INIT
#define INCLUDE_SYSCTL
#define INCLUDE_SYSCTL_HW
#define INCLUDE_SYSDBG_FLAG
#define INCLUDE_SYSLOG
#define INCLUDE_SYSTEMVIEWER_AGENT
#define INCLUDE_SYSTEM_TASK_PRIORITIES
#define INCLUDE_SYS_START
#define INCLUDE_SYS_TIMESTAMP
#define INCLUDE_TASK_CREATE_DELETE
#define INCLUDE_TASK_CREATE_HOOKS
#define INCLUDE_TASK_HOOKS
#define INCLUDE_TASK_HOOKS_SHOW
#define INCLUDE_TASK_INFO
#define INCLUDE_TASK_LIST
#define INCLUDE_TASK_OPEN
#define INCLUDE_TASK_RESTART
#define INCLUDE_TASK_SHELL_CMD
#define INCLUDE_TASK_SHOW
#define INCLUDE_TASK_STACK_ALLOC
#define INCLUDE_TASK_STACK_NO_EXEC
#define INCLUDE_TASK_SWAP_HOOKS
#define INCLUDE_TASK_SWITCH_ENTROPY_ADD
#define INCLUDE_TASK_SWITCH_HOOKS
#define INCLUDE_TASK_TOOLS_UTIL
#define INCLUDE_TIMER_OPEN
#define INCLUDE_TIMER_SYS
#define INCLUDE_TIMESTAMP
#define INCLUDE_TIMEX
#define INCLUDE_TIP
#define INCLUDE_TIP_CMD
#define INCLUDE_TLS
#define INCLUDE_TLS_LOADER_SUPPORT
#define INCLUDE_TRIGGERING
#define INCLUDE_TRIGGER_SHOW
#define INCLUDE_TRIG_DATACOLLECTOR
#define INCLUDE_TTY_DEV
#define INCLUDE_TYLIB
#define INCLUDE_UNLOADER
#define INCLUDE_UNLOADER_SHELL_CMD
#define INCLUDE_USER_APPL
#define INCLUDE_VIRTUAL_DISK
#define INCLUDE_VM_INVTBL
#define INCLUDE_VM_RTP
#define INCLUDE_VM_SHOW
#define INCLUDE_VM_SHOW_SHELL_CMD
#define INCLUDE_VXBUS
#define INCLUDE_VXBUS_PARAMS
#define INCLUDE_VXBUS_SHOW
#define INCLUDE_VXB_AUX_CLK
#define INCLUDE_VXB_SYS_CLK
#define INCLUDE_VXB_TIMESTAMP
#define INCLUDE_VXDBG
#define INCLUDE_VXDBG_CPU_CONTROL
#define INCLUDE_VXDBG_HOOK
#define INCLUDE_VXDBG_MODULE
#define INCLUDE_VXDBG_RTP
#define INCLUDE_VXDBG_RUNCTRL
#define INCLUDE_VXEVENTS
#define INCLUDE_VXIPI
#define INCLUDE_VXMEMPROBE_INIT
#define INCLUDE_VXMUX_MBLK
#define INCLUDE_VXMUX_NULLBUFPOOL
#define INCLUDE_VXSIM_IFCONFIG
#define INCLUDE_VXSIM_POSIX_CLOCKS
#define INCLUDE_VX_NATIVE_SCHEDULER
#define INCLUDE_VX_TRADITIONAL_SCHEDULER
#define INCLUDE_WATCHDOGS
#define INCLUDE_WATCHDOGS_CREATE_DELETE
#define INCLUDE_WATCHDOGS_SHOW
#define INCLUDE_WINDVIEW
#define INCLUDE_WINDVIEW_CLASS
#define INCLUDE_WINDVIEW_MODULE_CLASS
#define INCLUDE_WRS_VXSIM_WINDOWS
#define INCLUDE_WVUPLOAD_FILE
#define INCLUDE_XBD
#define INCLUDE_XBD_RAMDRV
#define INCLUDE_XDR
#undef INCLUDE_USE_IPCOM_SHELL
#undef INCLUDE_USE_NATIVE_SHELL
#undef INCLUDE_IPCOM_USE_VXSHELL_CMD
#undef INCLUDE_IPCOM_USE_RAM_DISK
#undef INCLUDE_IPCOM_FS_IPCOM
#undef INCLUDE_IPCOM_FS_NATIVE
#undef INCLUDE_IPTELNETS
#undef INCLUDE_USE_WAITIF
#undef INCLUDE_IPNET_IFCONFIG_2
#undef INCLUDE_IPNET_IFCONFIG_3
#undef INCLUDE_IPNET_IFCONFIG_4
#undef INCLUDE_IPDHCPC
#undef INCLUDE_IPAIP
#undef INCLUDE_IPAIP_GLOBAL_CONFIGS
#undef INCLUDE_IPAIP_INTERFACE_CONFIGS
#undef INCLUDE_IPPROXYARP
#undef INCLUDE_IPL2TP
#undef INCLUDE_IPCOM_USE_LINK_STUB
#undef INCLUDE_IPNET_USE_PPP
#undef INCLUDE_IPNET_USE_SOCKDEV
#undef INCLUDE_IPNET6_AUTOCONF_PRIVACY_EXT
#undef INCLUDE_IPNET6_PRIVACY_GLOBAL_CONFIGS
#undef INCLUDE_IPNET6_PRIVACY_INTERFACE_CONFIGS
#undef INCLUDE_IPNET_USE_NAT
#undef INCLUDE_IPTCPAO_CMD
#undef INCLUDE_IPARP_CMD
#undef INCLUDE_IPCOM_SHELL_CMD
#undef INCLUDE_IPCOM_SYSLOGD_CMD
#undef INCLUDE_IPCOM_SYSLOGD_USE_LOG_FILE
#undef INCLUDE_IPCOM_SYSVAR_CMD
#undef INCLUDE_IPECHO_CLIENT_CMD
#undef INCLUDE_IPECHO_SERVER_CMD
#undef INCLUDE_IPFTP_CMD
#undef INCLUDE_IPFTPC
#undef INCLUDE_IPIFCONFIG_CMD
#undef INCLUDE_IPD_CMD
#undef INCLUDE_IPNET_CTRL_CMD
#undef INCLUDE_IPMEM_DEBUG_CMD
#undef INCLUDE_IPNAT_CMD
#undef INCLUDE_IPNDP_CMD
#undef INCLUDE_IPNETSTAT_CMD
#undef INCLUDE_IPPING_CMD
#undef INCLUDE_IPPING6_CMD
#undef INCLUDE_IPRADVD_CMD
#undef INCLUDE_IPROUTE_CMD
#undef INCLUDE_IPIP_CMD
#undef INCLUDE_IPNET_PCAP_CMD
#undef INCLUDE_IPVCONFIG_CMD
#undef INCLUDE_IPSNTP_CMD
#undef INCLUDE_IPSNTPC_API
#undef INCLUDE_IPNTP_CMD
#undef INCLUDE_IPNTP
#undef INCLUDE_IPSOCKPERF_CMD
#undef INCLUDE_IPSOCKTEST_CMD
#undef INCLUDE_IPSVCONFIG_CMD
#undef INCLUDE_IPSYSCTL_CMD
#undef INCLUDE_IPTRACE_ROUTE_CMD
#undef INCLUDE_IPTCP_TEST_CMD
#undef INCLUDE_IPTFTP_CLIENT_CMD
#undef INCLUDE_IPTFTPC
#undef INCLUDE_IPCOM_USE_TIME_CMD
#undef INCLUDE_ERRNOS_CMD
#undef INCLUDE_IPVERSION_CMD
#undef INCLUDE_IPCOM_USE_MIB2_CMD
#undef INCLUDE_IPCOM_CPU_CMD
#undef INCLUDE_NETSMP_CMD
#undef INCLUDE_JOB_QUEUE_UTIL
#undef INCLUDE_ARP_API
#undef INCLUDE_IPWRAP_ARP
#undef INCLUDE_NETBUFADVLIB
#undef INCLUDE_NETPOOLSHOW
#undef INCLUDE_MBUF_UTIL2
#undef INCLUDE_NET_BOOT_IPV6_CFG
#undef INCLUDE_FTP6
#undef INCLUDE_GETADDRINFO
#undef INCLUDE_GETNAMEINFO
#undef INCLUDE_IPWRAP_GETNAMEINFO
#undef INCLUDE_GETNAMEINFO_SYSCTL
#undef INCLUDE_NET_HOST_SHOW
#undef INCLUDE_IFCONFIG
#undef INCLUDE_IFNAMELIB
#undef INCLUDE_NET_INIT_SKIP
#undef INCLUDE_NET_POOL
#undef INCLUDE_MUXTK
#undef INCLUDE_MUXTK_OVER_END
#undef INCLUDE_MUX_L2
#undef INCLUDE_MUX_IF_FUNC_DBASE
#undef INCLUDE_USER_PRE_NETWORK_APPL_INIT
#undef INCLUDE_VXMUX_CMD_VXSLAB
#undef INCLUDE_NET_BOOT_CONFIG
#undef INCLUDE_NET_INIT
#undef INCLUDE_MIB2_ALL
#undef INCLUDE_MIB2_ICMP
#undef INCLUDE_MIB2_IFMGT
#undef INCLUDE_END_POLLED_STATS
#undef INCLUDE_MIB2_IP
#undef INCLUDE_MIB2_SYSTEM
#undef INCLUDE_MIB2_TCP
#undef INCLUDE_MIB2_UDP
#undef INCLUDE_GETPROTOBYNAME
#undef INCLUDE_GETPROTOBYNUMBER
#undef INCLUDE_NETSTAT_UN_COMP
#undef INCLUDE_NETSTAT
#undef INCLUDE_IPWRAP_NETSTAT
#undef INCLUDE_PING6
#undef INCLUDE_IPWRAP_PING6
#undef INCLUDE_PING
#undef INCLUDE_IPWRAP_PING
#undef INCLUDE_IP6ATTACH
#undef INCLUDE_NET_DRV_HOME_DIR_REFLECT
#undef INCLUDE_RLOGIN
#undef INCLUDE_ROUTECMD
#undef INCLUDE_IPWRAP_ROUTECMD
#undef INCLUDE_TELNET_CLIENT
#undef INCLUDE_TFTP_CLIENT
#undef INCLUDE_SEC_CIPHER_AES_128_CBC
#undef INCLUDE_SEC_CIPHER_AES_128_ECB
#undef INCLUDE_SEC_CIPHER_AES_128_CTR
#undef INCLUDE_SEC_CIPHER_AES_192_CBC
#undef INCLUDE_SEC_CIPHER_AES_192_CTR
#undef INCLUDE_SEC_CIPHER_AES_256_CBC
#undef INCLUDE_SEC_CIPHER_AES_256_CTR
#undef INCLUDE_SEC_CIPHER_AES_256_ECB
#undef INCLUDE_SEC_CIPHER_BLOWFISH_CBC
#undef INCLUDE_SEC_CIPHER_CAST_CBC
#undef INCLUDE_SEC_CIPHER_DES_CBC
#undef INCLUDE_SEC_CIPHER_3DES_CBC
#undef INCLUDE_SEC_CIPHER_RC4
#undef INCLUDE_SEC_CIPHER_AES_128_CBC_OPENSSL
#undef INCLUDE_SEC_CIPHER_AES_128_CBC_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_AES_128_CTR_OPENSSL
#undef INCLUDE_SEC_CIPHER_AES_128_ECB_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_AES_128_ECB_OPENSSL
#undef INCLUDE_SEC_CIPHER_AES_128_CTR_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_AES_192_CBC_OPENSSL
#undef INCLUDE_SEC_CIPHER_AES_192_CTR_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_AES_192_CTR_OPENSSL
#undef INCLUDE_SEC_CIPHER_AES_192_CBC_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_AES_256_CBC_OPENSSL
#undef INCLUDE_SEC_CIPHER_AES_256_CBC_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_AES_256_CTR_OPENSSL
#undef INCLUDE_SEC_CIPHER_AES_256_CTR_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_AES_256_ECB_OPENSSL
#undef INCLUDE_SEC_CIPHER_AES_256_ECB_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_BLOWFISH_CBC_OPENSSL
#undef INCLUDE_SEC_CIPHER_BLOWFISH_CBC_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_CAST_CBC_OPENSSL
#undef INCLUDE_SEC_CIPHER_CAST_CBC_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_DES_CBC_OPENSSL
#undef INCLUDE_SEC_CIPHER_DES_CBC_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_3DES_CBC_OPENSSL
#undef INCLUDE_SEC_CIPHER_3DES_CBC_OPENSSL_EVP
#undef INCLUDE_SEC_CIPHER_RC4_OPENSSL
#undef INCLUDE_SEC_CIPHER_RC4_OPENSSL_EVP
#undef INCLUDE_SEC_SECRET
#undef INCLUDE_SEC_SECRET_CMD
#undef INCLUDE_SEC_VAULT_CMD
#undef INCLUDE_SEC_KEY_STORE
#undef INCLUDE_SEC_KEY_STORE_CMD
#undef INCLUDE_SEC_VAULT_KEP_OBFUSCATOR
#undef INCLUDE_SEC_VAULT
#undef INCLUDE_TRUST_STORE
#undef INCLUDE_STATIC_TRUST_STORE
#undef INCLUDE_CPU_LOW_PWR_IDLE
#undef INCLUDE_CPU_LIGHT_PWR_MGR
#undef INCLUDE_IPNET_USE_VLAN_STACKING
#undef INCLUDE_L2CONFIG
#undef INCLUDE_RPC
#undef INCLUDE_NFS2_CLIENT
#undef INCLUDE_NFS3_CLIENT
#undef INCLUDE_NFS_MOUNT_ALL
#undef INCLUDE_NFS2_SERVER
#undef INCLUDE_NFS3_SERVER
#undef INCLUDE_NFS_DEBUG
#undef INCLUDE_NFS_SERVER_INSTALL
#undef INCLUDE_IPCRYPTO
#undef INCLUDE_IPSSL
#undef INCLUDE_DEFAULT_TIMEZONE
#undef INCLUDE_DIAB_INTRINSICS
#undef INCLUDE_CPU_INIT
#undef INCLUDE_VXCPULIB
#undef INCLUDE_EDR_CUSTOM_POLICY
#undef INCLUDE_POSIX_CLOCKS_SET_FROM_RTC
#undef INCLUDE_POSIX_SPAWN
#undef INCLUDE_VXBUS_RTC_LIB
#undef INCLUDE_JITTER_TOOL
#undef INCLUDE_USER_PRE_KERNEL_APPL_INIT
#undef INCLUDE_USER_POST_KERNEL_APPL_INIT
#undef INCLUDE_TASK_ROTATE
#undef INCLUDE_TASK_UTIL
#undef INCLUDE_MEM_ALLOT
#undef INCLUDE_PX_SCHED_DEF_POLICIES
#undef INCLUDE_POSIX_PTHREAD_SCHEDULER
#undef INCLUDE_PX_SCHED_SPORADIC_POLICY
#undef INCLUDE_CUSTOM_SCHEDULER
#undef INCLUDE_STRING_SEARCH
#undef INCLUDE_GETPAGESIZE
#undef INCLUDE_SLL_CREATE_DELETE
#undef INCLUDE_DLL_CREATE_DELETE
#undef INCLUDE_SYSCTL_CLI
#undef INCLUDE_CUSTOM_ENTROPY_ADD
#undef INCLUDE_POSIX_TRACE_TIMESTAMP
#undef INCLUDE_POSIX_TRACE
#undef INCLUDE_MEM_EDR
#undef INCLUDE_KASAN
#undef INCLUDE_MEM_PART_CACHE
#undef INCLUDE_MEM_EDR2
#undef INCLUDE_KASAN2
#undef INCLUDE_USER_RESERVED_MEMORY
#undef INCLUDE_CACHE_COMPACT_DMA_SUPPORT
#undef INCLUDE_CORE_DUMP
#undef INCLUDE_CORE_DUMP_RTP
#undef INCLUDE_POSIX_SHM
#undef INCLUDE_POSIX_SHM_API
#undef INCLUDE_DEVMEM
#undef INCLUDE_MMU_OPTIMIZE
#undef INCLUDE_SPINLOCK_DEBUG
#undef INCLUDE_SPINLOCK_ND_TIMED
#undef INCLUDE_DEBUG_KPRINTF
#undef INCLUDE_DEBUG_KPUTS
#undef INCLUDE_DEBUG_KWRITE_USER
#undef INCLUDE_POSIX_ADVISORY_FILE_LOCKING
#undef INCLUDE_POSIX_PIPES
#undef INCLUDE_POSIX_THREAD_CPUTIME
#undef INCLUDE_VRFS
#undef INCLUDE_HRFS
#undef INCLUDE_HRFS_ACCESS_TIMESTAMP
#undef INCLUDE_HRFS_FORMAT
#undef INCLUDE_DEV_NULL
#undef INCLUDE_ANALYSIS_TEST
#undef INCLUDE_STANDALONE_SYM_TBL
#undef INCLUDE_SHELL_HISTORY_FILE
#undef INCLUDE_NET_SYM_TBL
#undef INCLUDE_IPCRYPTO_USE_CMDS
#undef INCLUDE_VERIFY_CMD
#undef INCLUDE_ASN1PARSE_CMD
#undef INCLUDE_REQ_CMD
#undef INCLUDE_DGST_CMD
#undef INCLUDE_DH_CMD
#undef INCLUDE_DHPARAM_CMD
#undef INCLUDE_GENDH_CMD
#undef INCLUDE_ENC_CMD
#undef INCLUDE_PASSWD_CMD
#undef INCLUDE_CA_CMD
#undef INCLUDE_CRL_CMD
#undef INCLUDE_RSA_CMD
#undef INCLUDE_RSAUTL_CMD
#undef INCLUDE_GENRSA_CMD
#undef INCLUDE_DSA_CMD
#undef INCLUDE_DSAPARAM_CMD
#undef INCLUDE_GENDSA_CMD
#undef INCLUDE_X509_CMD
#undef INCLUDE_SPEED_CMD
#undef INCLUDE_PKCS7_CMD
#undef INCLUDE_CRL2PKCS7_CMD
#undef INCLUDE_NSEQ_CMD
#undef INCLUDE_PKCS12_CMD
#undef INCLUDE_PKCS8_CMD
#undef INCLUDE_SPKAC_CMD
#undef INCLUDE_SMIME_CMD
#undef INCLUDE_RAND_CMD
#undef INCLUDE_VERSION_CMD
#undef INCLUDE_ENGINE_CMD
#undef INCLUDE_OCSP_CMD
#undef INCLUDE_ECPARAM_CMD
#undef INCLUDE_IPCRYPTO_USE_TEST_CMDS
#undef INCLUDE_SEC_HASH_MD5_OPENSSL_EVP
#undef INCLUDE_SEC_HASH_RMD_OPENSSL
#undef INCLUDE_SEC_HASH_RMD_OPENSSL_EVP
#undef INCLUDE_SEC_HASH_SHA1_OPENSSL_EVP
#undef INCLUDE_SEC_HASH_SHA256_OPENSSL_EVP
#undef INCLUDE_SEC_HASH_SHA384_OPENSSL
#undef INCLUDE_SEC_HASH_SHA384_OPENSSL_EVP
#undef INCLUDE_SEC_HASH_SHA512_OPENSSL
#undef INCLUDE_SEC_HASH_SHA512_OPENSSL_EVP
#undef INCLUDE_SEC_HASH_WHIRLPOOL_OPENSSL
#undef INCLUDE_SEC_HASH_WHIRLPOOL_OPENSSL_EVP
#undef INCLUDE_ERF_SHOW_ROUTINES
#undef INCLUDE_HRFS_READONLY
#undef INCLUDE_RAM_DISK_FORMAT_NONE
#undef INCLUDE_RAM_DISK_FORMAT_DOSFS
#undef INCLUDE_RAM_DISK_FORMAT_HRFS
#undef INCLUDE_FS_DEVICE_MOUNT_VALIDATE
#undef INCLUDE_FS_DEVICE_RENAME
#undef INCLUDE_FSINFO_SHOW
#undef INCLUDE_IPWRAP_IFSHOW
#undef INCLUDE_IPWRAP_GETHOSTBYNAME
#undef INCLUDE_IPWRAP_GETHOSTBYADDR
#undef INCLUDE_IPWRAP_IFNAME
#undef INCLUDE_IPWRAP_SNTPCTIMEGET
#undef INCLUDE_IPWRAP_SNTPSCLOCKSET
#undef INCLUDE_IPSNTPS_API
#undef INCLUDE_IPSNTPS
#undef INCLUDE_IPWRAP_SNTPSNSECTOFRACTION
#undef INCLUDE_IPWRAP_IFLIB
#undef INCLUDE_IPWRAP_IFLIB_TEST
#undef INCLUDE_IPWRAP_IF6LIB
#undef INCLUDE_IPWRAP_IF6LIB_TEST
#undef INCLUDE_IPWRAP_OLDROUTELIB
#undef INCLUDE_CORE_NFS_CLIENT
#undef INCLUDE_NFS_CLIENT_ALL
#undef INCLUDE_CORE_NFS_SERVER
#undef INCLUDE_NFS_SERVER_ALL
#undef INCLUDE_NFSD_START_DELAY
#undef INCLUDE_NFS_CLIENT_RPC_TCP
#undef INCLUDE_NFS_CLIENT_RPC_UDP
#undef INCLUDE_NFS_CLIENT_RPC_AUTO
#undef INCLUDE_ANALYSIS_TOP_DEMO
#undef INCLUDE_ANALYSIS_TOP_DEMO_START
#undef INCLUDE_ANALYSIS_CACHE_DEMO
#undef INCLUDE_ANALYSIS_MEM_DEMO
#undef INCLUDE_ANALYSIS_IO_DEMO
#undef INCLUDE_ANALYSIS_INTLATENCY_DEMO
#undef INCLUDE_ANALYSIS_USER_EVENT_DEMO
#undef INCLUDE_SEC_HASH_RMD
#undef INCLUDE_SEC_HASH_SHA384
#undef INCLUDE_SEC_HASH_SHA512
#undef INCLUDE_SEC_HASH_WHIRLPOOL
#undef INCLUDE_SEC_HASH_MD5_MBEDTLS
#undef INCLUDE_SEC_HASH_SHA1_MBEDTLS
#undef INCLUDE_SEC_HASH_SHA256_MBEDTLS
#undef INCLUDE_SEC_HASH_SHA512_MBEDTLS
#undef INCLUDE_IPCOM_USE_KEY_DB
#undef INCLUDE_IPCOM_KEY_DB_CMD
#undef INCLUDE_IPSSL_USE_CMDS
#undef INCLUDE_IPSSL_USE_TEST_CMDS
#undef INCLUDE_XBD_BLK_DEV
#undef INCLUDE_XBD_PART_LIB
#undef INCLUDE_XBD_BLK_CACHE
#undef INCLUDE_RAMDRV
#undef INCLUDE_MEMDRV
#undef INCLUDE_MVARDRV
#undef INCLUDE_IO_REALPATH
#undef INCLUDE_MKDIRP
#undef INCLUDE_LEGACY_DEV_NAME_LINKS
#undef INCLUDE_PATHNAME_RESOLUTION_LEGACY
#undef INCLUDE_VXNS_IOS
#undef INCLUDE_VDFS
#undef INCLUDE_UTF
#undef INCLUDE_OVERLAY_FS
#undef INCLUDE_EEPROMDRV
#undef INCLUDE_CRC
#undef INCLUDE_IPMCP
#undef INCLUDE_IPMCP_USE_IGMP
#undef INCLUDE_IPMCP_USE_MLD
#undef INCLUDE_IPMCAST_PROXY_CMD
#undef INCLUDE_IPRADIUS
#undef INCLUDE_IPRADIUS_CMD
#undef INCLUDE_FILESYSTEM_SYMLINK_CONFIG
#undef INCLUDE_IPDNSC
#undef INCLUDE_REMOTEPROC
#undef INCLUDE_REMOTEPROC_VIRTIO
#undef INCLUDE_RPMSG_VIRTIO
#undef INCLUDE_REMOTEPROC_LOADER
#undef INCLUDE_REMOTEPROC_AUTO_START
#undef INCLUDE_RPMSG
#undef INCLUDE_RTP_APPL_INIT_STRING
#undef INCLUDE_RTP_APPL_INIT_CMD_SHELL_SCRIPT
#undef INCLUDE_SC_REALPATH
#undef INCLUDE_RTP_CPU_USAGE_CTRL
#undef INCLUDE_RTP_RESOURCE_GROUP
#undef INCLUDE_RTP_MEM_ALLOC_CTRL
#undef INCLUDE_RTP_RESOURCE_GROUP_SHOW
#undef INCLUDE_STOP_MODE_AGENT_SERIAL
#undef INCLUDE_WVNETD
#undef INCLUDE_WVUPLOAD_SOCK
#undef INCLUDE_USER_TIMESTAMP
#undef INCLUDE_SEQ_TIMESTAMP
#undef INCLUDE_WV_BUFF_USER
#undef INCLUDE_UNIX
#undef INCLUDE_IPNSLOOKUP_CMD
#undef INCLUDE_IPFTPS
#undef INCLUDE_IPTFTP_COMMON
#undef INCLUDE_IPTFTPS
#undef INCLUDE_IPDHCPC6
#undef INCLUDE_IPDHCPC6_CMD
#undef INCLUDE_IPDHCPR
#undef INCLUDE_IPDHCPS6
#undef INCLUDE_IPDHCPS6_CMD
#undef INCLUDE_IPLDAPC
#undef INCLUDE_IPLDAPC_ADD_CMD
#undef INCLUDE_IPLDAPC_COMPARE_CMD
#undef INCLUDE_IPLDAPC_DELETE_CMD
#undef INCLUDE_IPLDAPC_MODIFY_CMD
#undef INCLUDE_IPLDAPC_MODIFYDN_CMD
#undef INCLUDE_IPLDAPC_SEARCH_CMD
#undef INCLUDE_IPSNTPC
#undef INCLUDE_IPSNTP_COMMON
#undef INCLUDE_IPPPP
#undef INCLUDE_IPPPPOE
#undef INCLUDE_IPPPPMP
#undef INCLUDE_IPPPP_VJCOMP
#undef INCLUDE_IPPPP_CMD
#undef INCLUDE_IPPPP_INTERFACE_CONFIG
#undef INCLUDE_IPPPP_USERS_CONFIG
#undef INCLUDE_XDR_BOOL_T
#undef INCLUDE_CORE_DUMP_SHOW
#undef INCLUDE_CORE_DUMP_MEM_FILTER
#undef INCLUDE_CORE_DUMP_MEM_POOL
#undef INCLUDE_CORE_DUMP_FULL_DATA
#undef INCLUDE_CORE_DUMP_MINIMAL_DATA
#undef INCLUDE_CORE_DUMP_COMPRESS
#undef INCLUDE_CORE_DUMP_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_COMMON_COMPRESS_ZLIB
#undef INCLUDE_CORE_DUMP_COMMON_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_UTIL
#undef INCLUDE_CORE_DUMP_MEM
#undef INCLUDE_CORE_DUMP_RTP_COMPRESS_ZLIB
#undef INCLUDE_CORE_DUMP_RTP_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_RTP_FS
#undef INCLUDE_ZLIB
#undef INCLUDE_KASAN_TEST
#undef INCLUDE_MEM_EDR_SHOW
#undef INCLUDE_MEM_EDR_RTP_SHOW
#undef INCLUDE_PAGE_SIZE_OPTIMIZATION
#undef INCLUDE_SC_POSIX_SHM
#undef INCLUDE_CACHE_DMA32_LIB
#undef INCLUDE_MEM_PART_CACHE_SHOW
#undef INCLUDE_MEM_EDR_SHELL_CMD
#undef INCLUDE_MEM_EDR_RTP_SHELL_CMD
#undef INCLUDE_HISTORY_FILE_SHELL_CMD
#undef INCLUDE_WRLOAD_CMD
#undef INCLUDE_CAFE_EP_HPC
#undef INCLUDE_ANALYSIS_HPC_TEST_HW
#undef INCLUDE_ANALYSIS_HPC_API_TEST_HW
#undef INCLUDE_BRIDGE
#undef INCLUDE_TAR
#undef INCLUDE_TIMESTAMP64
#undef INCLUDE_DMA_SYS
#undef INCLUDE_FLASH_SYS
#undef INCLUDE_GPIO_SYS
#undef INCLUDE_PINMUX_SYS
#undef INCLUDE_INT_SHOW
#undef INCLUDE_ISR_HANDLER_SHOW
#undef INCLUDE_INTCTLR_DYNAMIC_LIB
#undef INCLUDE_PCI_MSI
#undef INCLUDE_MAILBOX_SYS
#undef INCLUDE_MEM_DESC
#undef INCLUDE_PCI_BUS
#undef INCLUDE_PCI_SHOW
#undef INCLUDE_PCI_AUTOCONF
#undef INCLUDE_PCIE_AER
#undef INCLUDE_PCI_EP_SYS
#undef INCLUDE_PHY_SYS
#undef INCLUDE_POWERDOMAIN_SYS
#undef INCLUDE_REGMAP_SYS
#undef INCLUDE_SMP_SCHED_FEPT_POLICY
#undef INCLUDE_SMP_SCHED_SMT_POLICY
#undef INCLUDE_SPI_BUS
#undef INCLUDE_VXB_TIMESTAMP64
#undef INCLUDE_TIMER_SYS_SHOW
#undef INCLUDE_FREQUENCY_PRIORITY
#undef INCLUDE_PERIOD_PRIORITY
#undef INCLUDE_VRFS_ROOT_TIME_SYNC
#undef INCLUDE_REGULATOR_SYS
#undef DRV_GPIO_REGULATOR
#undef DRV_FIXED_REGULATOR
#undef INCLUDE_RESET_SYS
#undef INCLUDE_VXBUS_ATTACH_EDR_INJECTION
#undef INCLUDE_VXBUS_DRIVER_DEFER
#undef INCLUDE_VXBUS_IOCTL
#undef INCLUDE_VXBUS_IOCTL_SHOW
#undef INCLUDE_VXBUS_DMA_BUF_LIB
#undef INCLUDE_VXSIM_USER_SM
#undef INCLUDE_DOSFS_PRTMSG_LEVEL
#undef INCLUDE_HRFS_DEFAULT_WRITE_MODE
#undef INCLUDE_HRFS_HISPEED_WRITE_MODE
#undef INCLUDE_HRFS_CHKDSK
#undef INCLUDE_VNODE_DELAY_WRITE
#undef INCLUDE_DEVCLK_SYS
#undef INCLUDE_DEV_DRV
#undef INCLUDE_DEV_ZERO
#undef INCLUDE_DEV_RANDOM
#undef INCLUDE_DEV_URANDOM
#undef INCLUDE_DEV_ARANDOM
#undef INCLUDE_DEV_TTY
#undef INCLUDE_DEV_CONSOLE
#undef INCLUDE_DEV_FULL
#undef INCLUDE_TMP_DIR
#undef INCLUDE_EVDEV_DEMO_BASIC
#undef INCLUDE_EVDEV_LIB_PTR
#undef INCLUDE_EVDEV_LIB_TS
#undef INCLUDE_EVDEV_LIB_KBD
#undef INCLUDE_EVDEV_DEMO_TS_CAL
#undef DRV_TOUCH_SCREEN_TI_TSC2004
#undef DRV_KEYBOARD_VIRTUAL
#undef INCLUDE_EVDEV_LIB_KBD_MAP_US
#undef DRV_TOUCH_SCREEN_VIRTUAL_MT
#undef DRV_POINTER_VIRTUAL
#undef DRV_POINTER_VXSIM
#undef INCLUDE_EVDEV_LIB_CORE
#undef INCLUDE_EVDEV_LIB_KBD_SHELL_ATTACH
#undef INCLUDE_PATCH_STANDALONE_DTB
#undef INCLUDE_LOOPFS
#undef INCLUDE_RPMSG_KDRV
#undef DRV_SIO_FDT_NS16550
#undef DRV_SIO_IOCTL_SC
#undef DRV_SIO_PCI_NS16550
#undef DRV_SIO_FDT_KINETIS
#undef DRV_ADXL345
#undef INCLUDE_CHARACTERLCDDRV
#undef DRV_CLK_FIXED_RATE
#undef DRV_INTCTLR_CPM_PIC
#undef DRV_SIO_FDT_ARM_AMBA_PL011
#undef DRV_WDT_FDT_ARM_SBSA
#undef INCLUDE_WATCHDOGDRV
#undef DRV_TIMER_FDT_FSL_FTM
#undef DRV_FDT_FSL_IMX_PCIE
#undef DRV_FDT_FSLQSPI
#undef DRV_SRTC_FDT_FSL
#undef DRV_FSL_SPI
#undef DRV_FSL_VYBRID_ADC
#undef DRV_RTC_FDT_GOLDFISH
#undef DRV_FDT_GPIO_RESTART
#undef DRV_I2C_LCD
#undef DRV_GPIO_FDT_KINETIS
#undef DRV_TIMER_FDT_KINETIS
#undef DRV_FDT_NXP_FSPI
#undef DRV_FDT_NXPQSPI
#undef DRV_SENSOR_FDT_LM75
#undef DRV_SENSOR_FDT_MMA8451Q
#undef DRV_FDT_SP805_WATCHDOG
#undef DRV_TIMER_FDT_SYNOPSYS_DW_TIMER
#undef DRV_DMA_FDT_SYNOPSYS_DW_DMA
#undef DRV_FDT_SYNOPSYS_DW_GPIO
#undef DRV_SYNOPSYS_DW_I2C
#undef DRV_DW_I2C_COMMON
#undef DRV_FDT_SYNOPSYS_DW_SPI
#undef DRV_SYS_CON
#undef DRV_SYS_CON_REBOOT
#undef DRV_SYS_CON_POWEROFF
#undef DRV_RTC_FDT_ZYNQMP
#undef DRV_FSL_DMA
#undef DRV_DMA_FDT_FSL_EDMA
#undef DRV_DMA_FDT_FSL_EDMA3
#undef DRV_FSL_ESPI
#undef DRV_FSL_I2C
#undef DRV_FSL_MSI
#undef DRV_FSL_PCI
#undef DRV_I2C_EEPROM
#undef DRV_I2C_GPIO_FDT_MAX_731X
#undef DRV_I2C_PCA954X
#undef DRV_I2C_PAC193X
#undef DRV_I2C_PCFRTC
#undef DRV_I2C_RTC
#undef DRV_PINMUX_IA
#undef DRV_IA_TPM_INSTANCE_0
#undef DRV_IA_TPM
#undef DRV_MICROCHIP_PCIE
#undef DRV_INTCTLR_FDT_MPIC
#undef DRV_INTCTLR_FDT_NXP_IRQSTEER
#undef DRV_TIMER_OPENPIC
#undef DRV_PCI_ECAM
#undef DRV_PCI_BRIDGE_GENERIC
#undef DRV_PCI_VGA_STUB
#undef DRV_PDMA_FDT_SIFIVE
#undef DRV_QSPI_FDT_SIFIVE
#undef DRV_SPI_TPM
#undef DRV_TI_EDMA3
#undef DRV_BUS_VIRT
#undef DRV_VIRTUAL_TIMER_WATCHDOG
#undef DRV_HOST_SIO_VXSIM
#undef INCLUDE_HOST_SIO
#undef DRV_WATCHDOG_IOCTL_SC
#undef INCLUDE_VXSIM_SW_RANDOM_NUM_GEN
#undef INCLUDE_SCEP
#undef INCLUDE_ZLIB_DEFLATE
#undef INCLUDE_ZLIB_INFLATE


/*** PARAMETERS ***/

#undef  BSP_VERSION
#define BSP_VERSION "2.0.1.1"
#undef  BSP_REV
#define BSP_REV ""
#undef  IPCOM_ENABLE_USER_SHELL
#define IPCOM_ENABLE_USER_SHELL FALSE
#undef  IPCOM_START_SHELL
#define IPCOM_START_SHELL NULL
#undef  IFCONFIG_1
#define IFCONFIG_1 "ifname","devname driver","inet driver", "gateway driver"
#undef  IFCONFIG_LOOPBACK
#define IFCONFIG_LOOPBACK "ifname lo0","inet 127.0.0.1/32","inet6 ::1/128","inet6 FF01::1/16"
#undef  RADVD_IFNAME_LIST
#define RADVD_IFNAME_LIST ""
#undef  RADVD_IFLIST_ADV_MANAGED_FLAG
#define RADVD_IFLIST_ADV_MANAGED_FLAG ""
#undef  RADVD_IFLIST_ADV_OTHER_CONFIG_FLAG
#define RADVD_IFLIST_ADV_OTHER_CONFIG_FLAG ""
#undef  RADVD_IFLIST_ADV_LINK_MTU
#define RADVD_IFLIST_ADV_LINK_MTU ""
#undef  RADVD_IFLIST_ADV_REACHABLE_TIME
#define RADVD_IFLIST_ADV_REACHABLE_TIME ""
#undef  RADVD_IFLIST_ADV_RETRANS_TIMER
#define RADVD_IFLIST_ADV_RETRANS_TIMER ""
#undef  RADVD_IFLIST_ADV_CUR_HOP_LIMIT
#define RADVD_IFLIST_ADV_CUR_HOP_LIMIT ""
#undef  RADVD_IFLIST_ADV_HA_FLAG
#define RADVD_IFLIST_ADV_HA_FLAG ""
#undef  RADVD_IFLIST_ADV_INTERVAL_OPT
#define RADVD_IFLIST_ADV_INTERVAL_OPT ""
#undef  RADVD_IFLIST_ADV_HA_OPT
#define RADVD_IFLIST_ADV_HA_OPT ""
#undef  RADVD_IFLIST_HA_OPT_LIFETIME
#define RADVD_IFLIST_HA_OPT_LIFETIME ""
#undef  RADVD_IFLIST_HA_OPT_PREFERENCE
#define RADVD_IFLIST_HA_OPT_PREFERENCE ""
#undef  RADVD_IFLIST_HA_OPT_MOBILE_ROUTER
#define RADVD_IFLIST_HA_OPT_MOBILE_ROUTER ""
#undef  RADVD_IFLIST_MIN_RTR_ADV_INTERVAL
#define RADVD_IFLIST_MIN_RTR_ADV_INTERVAL ""
#undef  RADVD_IFLIST_MAX_RTR_ADV_INTERVAL
#define RADVD_IFLIST_MAX_RTR_ADV_INTERVAL ""
#undef  RADVD_IFLIST_ADV_DEFAULT_LIFETIME
#define RADVD_IFLIST_ADV_DEFAULT_LIFETIME ""
#undef  RADVD_IFLIST_ADV_PREFIX
#define RADVD_IFLIST_ADV_PREFIX ""
#undef  RADVD_IFLIST_PREFIX
#define RADVD_IFLIST_PREFIX ""
#undef  RADVD_IFLIST_MIN_DELAY_BETWEEN_RAS
#define RADVD_IFLIST_MIN_DELAY_BETWEEN_RAS ""
#undef  RADVD_IFLIST_PREFIX_ADV_ONLINK_FLAG
#define RADVD_IFLIST_PREFIX_ADV_ONLINK_FLAG ""
#undef  RADVD_IFLIST_PREFIX_ADV_AUTONOMOUS_FLAG
#define RADVD_IFLIST_PREFIX_ADV_AUTONOMOUS_FLAG ""
#undef  RADVD_IFLIST_PREFIX_ADV_RTR_ADDR_FLAG
#define RADVD_IFLIST_PREFIX_ADV_RTR_ADDR_FLAG ""
#undef  RADVD_IFLIST_PREFIX_ADV_VALID_LIFETIME
#define RADVD_IFLIST_PREFIX_ADV_VALID_LIFETIME ""
#undef  RADVD_IFLIST_PREFIX_ADV_PREFERRED_LIFETIME
#define RADVD_IFLIST_PREFIX_ADV_PREFERRED_LIFETIME ""
#undef  RADVD_IFLIST_PREFIX_ADV_VALID_LIFETIME_DECREMENT
#define RADVD_IFLIST_PREFIX_ADV_VALID_LIFETIME_DECREMENT ""
#undef  RADVD_IFLIST_PREFIX_ADV_PREFERRED_LIFETIME_DECREMENT
#define RADVD_IFLIST_PREFIX_ADV_PREFERRED_LIFETIME_DECREMENT ""
#undef  RADVD_TASK_PRIORITY
#define RADVD_TASK_PRIORITY "50"
#undef  IPNET_MAX_INPUT_PKTS
#define IPNET_MAX_INPUT_PKTS 100
#undef  IPNET_BUSY_TASK_PRIORITY
#define IPNET_BUSY_TASK_PRIORITY 100
#undef  IPNET_REASSEMBLY_TIMEOUT
#define IPNET_REASSEMBLY_TIMEOUT 60
#undef  IPNET_MEMORY_LIMIT
#define IPNET_MEMORY_LIMIT 16777216
#undef  IPNET_DST_CACHE_LIMIT
#define IPNET_DST_CACHE_LIMIT 0
#undef  IPNET_MAX_REASSEMBLY_LIST_LEN
#define IPNET_MAX_REASSEMBLY_LIST_LEN 4
#undef  IPNET_MAX_DGRAM_FRAG_LIST_LEN
#define IPNET_MAX_DGRAM_FRAG_LIST_LEN 54
#undef  IPNET_SLAB_DESC_0
#define IPNET_SLAB_DESC_0 IPNET_ETH_MTU, IPCOM_SLAB_F_AVERAGE, 2
#undef  IPNET_SLAB_DESC_1
#define IPNET_SLAB_DESC_1 3000, IPCOM_SLAB_F_FEW, 4
#undef  IPNET_SLAB_DESC_2
#define IPNET_SLAB_DESC_2 10000, IPCOM_SLAB_F_ONE, 12
#undef  IPNET_SLAB_DESC_3
#define IPNET_SLAB_DESC_3 IPNET_PKT_POOL_MAX_MTU + 1, IPCOM_SLAB_F_ONE, 8
#undef  IPNET_SLAB_DESC_4
#define IPNET_SLAB_DESC_4 0
#undef  IPNET_SLAB_DESC_5
#define IPNET_SLAB_DESC_5 0
#undef  IPNET_INTERCOM_CONGESTION_LIMIT
#define IPNET_INTERCOM_CONGESTION_LIMIT 128
#undef  INET_MIN_MTU_SIZE
#define INET_MIN_MTU_SIZE 576
#undef  INET_BASE_HOP_LIMIT
#define INET_BASE_HOP_LIMIT "64"
#undef  INET_SEND_GRATUITOUS_ARP
#define INET_SEND_GRATUITOUS_ARP "yes"
#undef  INET_DELETE_ADDR_ON_DUPLICATE_DETECT
#define INET_DELETE_ADDR_ON_DUPLICATE_DETECT "yes"
#undef  INET_MAX_PKTS_PENDING
#define INET_MAX_PKTS_PENDING "3"
#undef  INET_MAX_UNICAST_SOLICIT
#define INET_MAX_UNICAST_SOLICIT "1"
#undef  INET_MAX_MULTICAST_SOLICIT
#define INET_MAX_MULTICAST_SOLICIT "9"
#undef  INET_MAX_APP_SOLICIT
#define INET_MAX_APP_SOLICIT "1"
#undef  INET_BASE_REACHABLE_TIME
#define INET_BASE_REACHABLE_TIME "30"
#undef  INET_BASE_RETRANSMIT_TIME
#define INET_BASE_RETRANSMIT_TIME "1"
#undef  INET_DELAY_FIRST_PROBE_TIME
#define INET_DELAY_FIRST_PROBE_TIME "5"
#undef  INET_NBR_CACHE_TO_LIVE_TIME
#define INET_NBR_CACHE_TO_LIVE_TIME "1200"
#undef  INET_DST_CACHE_TO_LIVE_TIME
#define INET_DST_CACHE_TO_LIVE_TIME "600"
#undef  INET_NBR_MIN_RANDOM_FACTOR
#define INET_NBR_MIN_RANDOM_FACTOR "50"
#undef  INET_NBR_MAX_RANDOM_FACTOR
#define INET_NBR_MAX_RANDOM_FACTOR "150"
#undef  INET_DISABLE_BROADCAST_FWD
#define INET_DISABLE_BROADCAST_FWD "1"
#undef  INET_ICMP_RATE_LIMIT_BUCKET_SIZE
#define INET_ICMP_RATE_LIMIT_BUCKET_SIZE "25000"
#undef  INET_ICMP_RATE_LIMIT_INTERVAL
#define INET_ICMP_RATE_LIMIT_INTERVAL "1000"
#undef  INET_ICMP_REDIRECT_SEND
#define INET_ICMP_REDIRECT_SEND "2"
#undef  INET_ICMP_REDIRECT_RECEIVE
#define INET_ICMP_REDIRECT_RECEIVE "1"
#undef  INET_ICMP_IGNORE_ECHO_REQ
#define INET_ICMP_IGNORE_ECHO_REQ "0"
#undef  INET_ICMP_IGNORE_TIMESTAMP_REQ
#define INET_ICMP_IGNORE_TIMESTAMP_REQ "0"
#undef  INET_ICMP_SEND_TIME_EXCEEDED
#define INET_ICMP_SEND_TIME_EXCEEDED "1"
#undef  INET_ICMP_SEND_DST_UNREACHABLE
#define INET_ICMP_SEND_DST_UNREACHABLE "1"
#undef  INET_ICMP_IGNORE_BROADCAST
#define INET_ICMP_IGNORE_BROADCAST "1"
#undef  INET_UDP_CHECKSUM
#define INET_UDP_CHECKSUM "1"
#undef  INET_RANDOM_IP_ID
#define INET_RANDOM_IP_ID "0"
#undef  INET6_MIN_MTU_SIZE
#define INET6_MIN_MTU_SIZE 1280
#undef  INET6_BASE_HOP_LIMIT
#define INET6_BASE_HOP_LIMIT "64"
#undef  INET6_MAX_PKTS_PENDING
#define INET6_MAX_PKTS_PENDING "3"
#undef  INET6_MAX_UNICAST_SOLICIT
#define INET6_MAX_UNICAST_SOLICIT "3"
#undef  INET6_MAX_MULTICAST_SOLICIT
#define INET6_MAX_MULTICAST_SOLICIT "0"
#undef  INET6_MAX_APP_SOLICIT
#define INET6_MAX_APP_SOLICIT "1"
#undef  INET6_DAD_TRANSMITS
#define INET6_DAD_TRANSMITS "1"
#undef  INET6_BASE_REACHABLE_TIME
#define INET6_BASE_REACHABLE_TIME "30"
#undef  INET6_BASE_RETRANSMIT_TIME
#define INET6_BASE_RETRANSMIT_TIME "1"
#undef  INET6_DELAY_FIRST_PROBE_TIME
#define INET6_DELAY_FIRST_PROBE_TIME "5"
#undef  INET6_NBR_CACHE_TO_LIVE_TIME
#define INET6_NBR_CACHE_TO_LIVE_TIME "1200"
#undef  INET6_DST_CACHE_TO_LIVE_TIME
#define INET6_DST_CACHE_TO_LIVE_TIME "600"
#undef  INET6_ROUTER_LIFETIME
#define INET6_ROUTER_LIFETIME "1800"
#undef  INET6_ICMP_RATE_LIMIT_BUCKET_SIZE
#define INET6_ICMP_RATE_LIMIT_BUCKET_SIZE "100"
#undef  INET6_ICMP_RATE_LIMIT_INTERVAL
#define INET6_ICMP_RATE_LIMIT_INTERVAL "1000"
#undef  INET6_ICMP_REDIRECT_SEND
#define INET6_ICMP_REDIRECT_SEND "2"
#undef  INET6_ICMP_REDIRECT_RECEIVE
#define INET6_ICMP_REDIRECT_RECEIVE "1"
#undef  INET6_ICMP_IGNORE_ECHO_REQ
#define INET6_ICMP_IGNORE_ECHO_REQ "0"
#undef  INET6_ICMP_SEND_TIME_EXCEEDED
#define INET6_ICMP_SEND_TIME_EXCEEDED "1"
#undef  INET6_ICMP_SEND_DST_UNREACHABLE
#define INET6_ICMP_SEND_DST_UNREACHABLE "1"
#undef  INET6_ACCEPT_RTADV
#define INET6_ACCEPT_RTADV "1"
#undef  INET6_AUTO_CONFIG
#define INET6_AUTO_CONFIG "1"
#undef  INET6_ADD_AUTONOMOUS_ADDR
#define INET6_ADD_AUTONOMOUS_ADDR "yes"
#undef  INET6_RTHDR0
#define INET6_RTHDR0 "0"
#undef  INET6_DISCARD_UDP_WITH_ZERO_CHECKSUM
#define INET6_DISCARD_UDP_WITH_ZERO_CHECKSUM "1"
#undef  TCP_CONN_TIMEOUT
#define TCP_CONN_TIMEOUT 75
#undef  TCP_MAX_RETRANSMITS
#define TCP_MAX_RETRANSMITS 10
#undef  TCP_MSL
#define TCP_MSL 30
#undef  TCP_DELAY_ACK_TIME
#define TCP_DELAY_ACK_TIME 200
#undef  IPTCP_MAX_RETRAMSMITS_IN_TRANSIENT
#define IPTCP_MAX_RETRAMSMITS_IN_TRANSIENT 2
#undef  TCP_IMMEDIATE_ACK_FOR_PSH
#define TCP_IMMEDIATE_ACK_FOR_PSH 1
#undef  IPTCP_MAX_TRANSIENT
#define IPTCP_MAX_TRANSIENT 20
#undef  IPTCP_TRANSIENT_THRESH
#define IPTCP_TRANSIENT_THRESH 5
#undef  TCP_MAX_MSS
#define TCP_MAX_MSS 0
#undef  TCP_USE_TIMESTAMP
#define TCP_USE_TIMESTAMP 1
#undef  TCP_USE_RFC1122_URGENT_DATA
#define TCP_USE_RFC1122_URGENT_DATA 0
#undef  TCP_SEGMENT_MULTIPLIER
#define TCP_SEGMENT_MULTIPLIER 2
#undef  TCP_LAND_ATTACK_PROTECTION
#define TCP_LAND_ATTACK_PROTECTION 1
#undef  TCP_ALLOW_ZERO_WINDOW
#define TCP_ALLOW_ZERO_WINDOW 0
#undef  TCP_ALLOW_TINY_WINDOW
#define TCP_ALLOW_TINY_WINDOW 1
#undef  TCP_PERSIST_TMO
#define TCP_PERSIST_TMO 0
#undef  TCP_CLAMP_MSS
#define TCP_CLAMP_MSS 0
#undef  TCP_DEFAULT_BACKLOG_SIZE
#define TCP_DEFAULT_BACKLOG_SIZE 5
#undef  TCP_KEEP_IDLE
#define TCP_KEEP_IDLE 7200
#undef  TCP_KEEP_INTVL
#define TCP_KEEP_INTVL 75
#undef  TCP_KEEP_CNT
#define TCP_KEEP_CNT 10
#undef  TCP_USE_RFC6528_SECURE_ISN
#define TCP_USE_RFC6528_SECURE_ISN 1
#undef  TCP_FORCE_IM_ACK_CNT
#define TCP_FORCE_IM_ACK_CNT 2
#undef  TCP_CHALLENGE_ACK_CNT
#define TCP_CHALLENGE_ACK_CNT "100"
#undef  TCP_MIN_RTO
#define TCP_MIN_RTO 1000
#undef  IPNET_SOCK_ANON_PORT_MIN
#define IPNET_SOCK_ANON_PORT_MIN "49152"
#undef  IPNET_SOCK_ANON_PORT_MAX
#define IPNET_SOCK_ANON_PORT_MAX "65535"
#undef  IPNET_SOCK_DEFAULT_SEND_BUFSIZE
#define IPNET_SOCK_DEFAULT_SEND_BUFSIZE "100000"
#undef  IPNET_SOCK_DEFAULT_RECV_BUFSIZE
#define IPNET_SOCK_DEFAULT_RECV_BUFSIZE "60000"
#undef  IPNET_SOCK_ADDR_NOTIFY
#define IPNET_SOCK_ADDR_NOTIFY "1"
#undef  IPNET_SOCK_ASSIGN_RANDOM
#define IPNET_SOCK_ASSIGN_RANDOM "no"
#undef  IPNET_ROUTE_MAX_CLONE_COUNT
#define IPNET_ROUTE_MAX_CLONE_COUNT "256"
#undef  IPNET_ROUTE_NEIGH_STALE_CORRECT
#define IPNET_ROUTE_NEIGH_STALE_CORRECT "yes"
#undef  IPNET_ROUTE_NEIGH_RATE_PERIOD
#define IPNET_ROUTE_NEIGH_RATE_PERIOD "100"
#undef  IPNET_ROUTE_NEIGH_RATE_LIMIT
#define IPNET_ROUTE_NEIGH_RATE_LIMIT "0"
#undef  NETBUF_LEADING_CLSPACE_DRV
#define NETBUF_LEADING_CLSPACE_DRV 64
#undef  NET_JOB_NUM_CFG
#define NET_JOB_NUM_CFG 85
#undef  NET_TASK_DEFAULT_PRIORITY
#define NET_TASK_DEFAULT_PRIORITY 50
#undef  NET_TASK_PRIORITIES
#define NET_TASK_PRIORITIES ""
#undef  NET_TASK_OPTIONS
#define NET_TASK_OPTIONS VX_SUPERVISOR_MODE | VX_UNBREAKABLE | VX_FP_TASK
#undef  NET_TASK_STACKSIZE
#define NET_TASK_STACKSIZE 20000
#undef  NUM_NET_DAEMONS
#define NUM_NET_DAEMONS 1
#undef  NET_DAEMONS_CPU_AFFINITY
#define NET_DAEMONS_CPU_AFFINITY TRUE
#undef  NET_DAEMONS_CPU_AFFINITIES
#define NET_DAEMONS_CPU_AFFINITIES ""
#undef  NETDRV_OPTIONS
#define NETDRV_OPTIONS 0
#undef  FTP_TRANSIENT_MAX_RETRY_COUNT
#define FTP_TRANSIENT_MAX_RETRY_COUNT 100
#undef  FTP_TRANSIENT_RETRY_INTERVAL
#define FTP_TRANSIENT_RETRY_INTERVAL 0
#undef  FTP_TRANSIENT_FATAL
#define FTP_TRANSIENT_FATAL ftpTransientFatal
#undef  FTP_DEBUG_OPTIONS
#define FTP_DEBUG_OPTIONS 0
#undef  FTP_TIMEOUT
#define FTP_TIMEOUT 0
#undef  MIB2IF_TRAP_RTN
#define MIB2IF_TRAP_RTN NULL
#undef  MIB2IF_TRAP_ARG
#define MIB2IF_TRAP_ARG NULL
#undef  MIB2IF_LONG_COUNTERS
#define MIB2IF_LONG_COUNTERS FALSE
#undef  RSH_STDERR_SETUP_TIMEOUT
#define RSH_STDERR_SETUP_TIMEOUT -1
#undef  REM_NUM_CONN_RETRIALS
#define REM_NUM_CONN_RETRIALS 3
#undef  CLEAR_BSS
#define CLEAR_BSS
#undef  UMASK_DEFAULT
#define UMASK_DEFAULT 022
#undef  MQ_HASH_SIZE
#define MQ_HASH_SIZE 0
#undef  KERN_PTHREAD_STACK_SIZE_DEFAULT
#define KERN_PTHREAD_STACK_SIZE_DEFAULT 20000
#undef  NUM_SIGNAL_QUEUES
#define NUM_SIGNAL_QUEUES 16
#undef  TIMER_SETTIME_RESTRICTED
#define TIMER_SETTIME_RESTRICTED FALSE
#undef  HIGH_RES_POSIX_CLOCK
#define HIGH_RES_POSIX_CLOCK FALSE
#undef  POSIX_CLOCK_TIMER
#define POSIX_CLOCK_TIMER NULL
#undef  BOOT_LINE_SIZE
#define BOOT_LINE_SIZE 1500
#undef  BOOT_LINE_ADRS
#define BOOT_LINE_ADRS (LOCAL_MEM_LOCAL_ADRS + BOOT_LINE_OFFSET)
#undef  BOOT_LINE_OFFSET
#define BOOT_LINE_OFFSET 0x0
#undef  DEFAULT_BOOT_LINE
#define DEFAULT_BOOT_LINE "ei(0,0)host:/usr/vw/config/bsp/vxWorks                         h=90.0.0.3 e=90.0.0.50 u=target"
#undef  ROOT_STACK_SIZE
#define ROOT_STACK_SIZE 20000
#undef  ISR_STACK_SIZE
#define ISR_STACK_SIZE 50000
#undef  INT_LOCK_LEVEL
#define INT_LOCK_LEVEL 0x01
#undef  TASK_USER_EXC_STACK_SIZE
#define TASK_USER_EXC_STACK_SIZE (8192*3)
#undef  TASK_KERNEL_EXC_STACK_SIZE
#define TASK_KERNEL_EXC_STACK_SIZE KERNEL_TASK_EXC_STACK_SIZE
#undef  TASK_USER_EXC_STACK_OVERFLOW_SIZE
#define TASK_USER_EXC_STACK_OVERFLOW_SIZE VM_PAGE_SIZE
#undef  TASK_USER_EXEC_STACK_OVERFLOW_SIZE
#define TASK_USER_EXEC_STACK_OVERFLOW_SIZE VM_PAGE_SIZE
#undef  TASK_USER_EXEC_STACK_UNDERFLOW_SIZE
#define TASK_USER_EXEC_STACK_UNDERFLOW_SIZE VM_PAGE_SIZE
#undef  TASK_KERNEL_EXEC_STACK_OVERFLOW_SIZE
#define TASK_KERNEL_EXEC_STACK_OVERFLOW_SIZE VM_PAGE_SIZE
#undef  TASK_KERNEL_EXEC_STACK_UNDERFLOW_SIZE
#define TASK_KERNEL_EXEC_STACK_UNDERFLOW_SIZE VM_PAGE_SIZE
#undef  TASK_KERNEL_EXC_STACK_OVERFLOW_SIZE
#define TASK_KERNEL_EXC_STACK_OVERFLOW_SIZE 0
#undef  TASK_PRIORITY_SET_COMPATIBLE
#define TASK_PRIORITY_SET_COMPATIBLE FALSE
#undef  WIND_JOBS_MAX
#define WIND_JOBS_MAX 64
#undef  VX_GLOBAL_NO_STACK_FILL
#define VX_GLOBAL_NO_STACK_FILL FALSE
#undef  MAX_REBOOT_HOOKS
#define MAX_REBOOT_HOOKS 8
#undef  ENV_VAR_USE_HOOKS
#define ENV_VAR_USE_HOOKS TRUE
#undef  MAX_ISR_JOBS
#define MAX_ISR_JOBS 16
#undef  EXC_TASK_PRIORITY
#define EXC_TASK_PRIORITY 0
#undef  JOB_TASK_STACK_SIZE
#define JOB_TASK_STACK_SIZE 32768
#undef  JOB_TASK_PRIORITY
#define JOB_TASK_PRIORITY 0
#undef  FUNCPTR_OBJ_MEMALLOC_RTN
#define FUNCPTR_OBJ_MEMALLOC_RTN memPartAlignedAlloc
#undef  FUNCPTR_OBJ_MEMFREE_RTN
#define FUNCPTR_OBJ_MEMFREE_RTN memPartFree
#undef  OBJ_MEM_POOL_ID
#define OBJ_MEM_POOL_ID memSysPartId
#undef  OBJ_LIBRARY_OPTIONS
#define OBJ_LIBRARY_OPTIONS 0
#undef  VXEVENTS_OPTIONS
#define VXEVENTS_OPTIONS EVENTS_NONINTERRUPTIBLE
#undef  SEM_RW_MAX_CONCURRENT_READERS
#define SEM_RW_MAX_CONCURRENT_READERS 32
#undef  VX_MAX_TASK_CREATE_RTNS
#define VX_MAX_TASK_CREATE_RTNS 40
#undef  MEM_PART_DEFAULT_OPTIONS
#define MEM_PART_DEFAULT_OPTIONS (MEM_ALLOC_ERROR_LOG_FLAG | MEM_ALLOC_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_LOG_FLAG | MEM_BLOCK_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_SUSPEND_FLAG | MEM_BLOCK_CHECK)
#undef  KERNEL_PROXIMITY_HEAP_SIZE
#define KERNEL_PROXIMITY_HEAP_SIZE 0x1000000
#undef  KERNEL_COMMON_HEAP_INIT_SIZE
#define KERNEL_COMMON_HEAP_INIT_SIZE 0x1000000
#undef  KERNEL_COMMON_HEAP_INCR_SIZE
#define KERNEL_COMMON_HEAP_INCR_SIZE 0x200000
#undef  POSIX_SIGNAL_MODE
#define POSIX_SIGNAL_MODE TRUE
#undef  EDR_PM_ARENA
#define EDR_PM_ARENA pmDefaultArena
#undef  PM_RESERVED_MEM
#define PM_RESERVED_MEM 0x400000
#undef  EDR_ERRLOG_SIZE
#define EDR_ERRLOG_SIZE (pmFreeSpace (EDR_PM_ARENA) / 4)
#undef  EDR_RECORD_SIZE
#define EDR_RECORD_SIZE VM_PAGE_SIZE
#undef  VX_NATIVE_SCHED_CONSTANT_RDY_Q
#define VX_NATIVE_SCHED_CONSTANT_RDY_Q VX_TRAD_SCHED_CONSTANT_RDY_Q
#undef  VX_TRAD_SCHED_CONSTANT_RDY_Q
#define VX_TRAD_SCHED_CONSTANT_RDY_Q TRUE
#undef  MAX_LOG_MSGS
#define MAX_LOG_MSGS 50
#undef  LOG_TASK_PRIORITY
#define LOG_TASK_PRIORITY 0
#undef  NUM_EARLY_SYSLOG_MSGS
#define NUM_EARLY_SYSLOG_MSGS 0
#undef  HOST_NAME_DEFAULT
#define HOST_NAME_DEFAULT "bootHost"
#undef  TARGET_NAME_DEFAULT
#define TARGET_NAME_DEFAULT "vxTarget"
#undef  HOST_USER_DEFAULT
#define HOST_USER_DEFAULT "target"
#undef  HOST_PASSWORD_DEFAULT
#define HOST_PASSWORD_DEFAULT ""
#undef  SCRIPT_DEFAULT
#define SCRIPT_DEFAULT ""
#undef  OTHER_DEFAULT
#define OTHER_DEFAULT ""
#undef  INTERRUPT_STACK_OVERFLOW_SIZE
#define INTERRUPT_STACK_OVERFLOW_SIZE VM_PAGE_SIZE
#undef  INTERRUPT_STACK_UNDERFLOW_SIZE
#define INTERRUPT_STACK_UNDERFLOW_SIZE VM_PAGE_SIZE
#undef  DKM_TLS_SIZE
#define DKM_TLS_SIZE 0
#undef  DKM_TLS_MAX_ALIGNMENT
#define DKM_TLS_MAX_ALIGNMENT 16
#undef  RANDOM_TASK_SWITCH_ROUNDS
#define RANDOM_TASK_SWITCH_ROUNDS 256
#undef  RANDOM_INTERRUPT_ROUNDS
#define RANDOM_INTERRUPT_ROUNDS 256
#undef  USER_I_MMU_ENABLE
#define USER_I_MMU_ENABLE
#undef  USER_D_MMU_ENABLE
#define USER_D_MMU_ENABLE
#undef  VX_SMP_NUM_CPUS
#define VX_SMP_NUM_CPUS 2
#undef  ENABLE_ALL_CPUS
#define ENABLE_ALL_CPUS TRUE
#undef  VX_ENABLE_CPU_TIMEOUT
#define VX_ENABLE_CPU_TIMEOUT 5
#undef  VX_SMP_CPU_EXPLICIT_RESERVE
#define VX_SMP_CPU_EXPLICIT_RESERVE ""
#undef  TARGET_HOSTNAME_DEFAULT
#define TARGET_HOSTNAME_DEFAULT "vxtarget"
#undef  LOCAL_MEM_LOCAL_ADRS
#define LOCAL_MEM_LOCAL_ADRS 0x180000000
#undef  LOCAL_MEM_SIZE
#define LOCAL_MEM_SIZE 0x10000000
#undef  VEC_BASE_ADRS
#define VEC_BASE_ADRS 0
#undef  EXC_MSG_ADRS
#define EXC_MSG_ADRS (LOCAL_MEM_LOCAL_ADRS + EXC_MSG_OFFSET)
#undef  EXC_MSG_OFFSET
#define EXC_MSG_OFFSET 0xA20
#undef  EXC_MSG_SIZE
#define EXC_MSG_SIZE (DTB_RELOC_ADDR - EXC_MSG_ADRS)
#undef  ROM_WARM_ADRS
#define ROM_WARM_ADRS (0x0)
#undef  STACK_SAVE
#define STACK_SAVE 0x40
#undef  RAM_HIGH_ADRS
#define RAM_HIGH_ADRS 0xffffffffffffffff
#undef  RAM_LOW_ADRS
#define RAM_LOW_ADRS 0x180010000
#undef  KERNEL_LOAD_ADRS
#define KERNEL_LOAD_ADRS 0x00100000
#undef  DEBUG_AGENT_TASK_PRIORITY
#define DEBUG_AGENT_TASK_PRIORITY 49
#undef  DEBUG_AGENT_CONFIG
#define DEBUG_AGENT_CONFIG NULL
#undef  DEBUG_AGENT_MEM_SIZE
#define DEBUG_AGENT_MEM_SIZE 256*1024
#undef  DEVICE_MANAGER_MAX_NUM_DEVICES
#define DEVICE_MANAGER_MAX_NUM_DEVICES 255
#undef  ERF_MAX_USR_CATEGORIES
#define ERF_MAX_USR_CATEGORIES 16
#undef  ERF_MAX_USR_TYPES
#define ERF_MAX_USR_TYPES 16
#undef  ERF_TASK_STACK_SIZE
#define ERF_TASK_STACK_SIZE 4096
#undef  ERF_MAX_EVENT_QUEUE_SIZE
#define ERF_MAX_EVENT_QUEUE_SIZE 256
#undef  ERF_EVENT_TASK_OPTIONS
#define ERF_EVENT_TASK_OPTIONS (VX_FP_TASK | VX_UNBREAKABLE)
#undef  RAM_DISK_BLK_SIZE
#define RAM_DISK_BLK_SIZE 512
#undef  RAM_DISK_SIZE
#define RAM_DISK_SIZE 0x800000
#undef  RAM_DISK_DEV_NAME
#define RAM_DISK_DEV_NAME "/ram0"
#undef  RAM_DISK_PART_SUPPORT
#define RAM_DISK_PART_SUPPORT FALSE
#undef  END_NET_JOB_INIT_STRING
#define END_NET_JOB_INIT_STRING "dummy0:0|dummy1:1"
#undef  MAX_LIO_CALLS
#define MAX_LIO_CALLS 0
#undef  MAX_AIO_SYS_TASKS
#define MAX_AIO_SYS_TASKS 0
#undef  AIO_TASK_PRIORITY
#define AIO_TASK_PRIORITY 0
#undef  AIO_TASK_STACK_SIZE
#define AIO_TASK_STACK_SIZE 0
#undef  NUM_DRIVERS
#define NUM_DRIVERS 32
#undef  NUM_FILES
#define NUM_FILES 50
#undef  MAX_FD_TABLE_SIZE
#define MAX_FD_TABLE_SIZE 2048
#undef  PIPE_MAX_OPEN_FDS
#define PIPE_MAX_OPEN_FDS 16
#undef  TYLIB_XOFF_PCNT
#define TYLIB_XOFF_PCNT 85
#undef  TYLIB_XON_PCNT
#define TYLIB_XON_PCNT 50
#undef  TYLIB_WRT_THRESHLD
#define TYLIB_WRT_THRESHLD 50
#undef  TYLIB_MON_TRAP_DISABLE
#define TYLIB_MON_TRAP_DISABLE FALSE
#undef  SELECT_FDSET_OVERSIZE_ALLOW
#define SELECT_FDSET_OVERSIZE_ALLOW FALSE
#undef  STORE_ABS_SYMBOLS
#define STORE_ABS_SYMBOLS FALSE
#undef  WV_RBUFF_MGR_PRIORITY
#define WV_RBUFF_MGR_PRIORITY 48
#undef  RTP_HOOK_TBL_SIZE
#define RTP_HOOK_TBL_SIZE 16
#undef  SYSCALL_HOOK_TBL_SIZE
#define SYSCALL_HOOK_TBL_SIZE 8
#undef  RTP_SIGNAL_QUEUE_SIZE
#define RTP_SIGNAL_QUEUE_SIZE 32
#undef  RTP_HEAP_INIT_SIZE
#define RTP_HEAP_INIT_SIZE 0x10000
#undef  RTP_HEAP_DEFAULT_OPTIONS
#define RTP_HEAP_DEFAULT_OPTIONS (MEM_ALLOC_ERROR_LOG_FLAG | MEM_ALLOC_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_LOG_FLAG | MEM_BLOCK_ERROR_EDR_FATAL_FLAG | MEM_BLOCK_CHECK)
#undef  RTP_FD_NUM_MAX
#define RTP_FD_NUM_MAX 20
#undef  RTP_MEM_FILL
#define RTP_MEM_FILL TRUE
#undef  SD_HOOK_TBL_SIZE
#define SD_HOOK_TBL_SIZE 8
#undef  SHELL_TASK_NAME_BASE
#define SHELL_TASK_NAME_BASE "tShell"
#undef  SHELL_TASK_OPTIONS
#define SHELL_TASK_OPTIONS (VX_FP_TASK | VX_UNBREAKABLE | COPROCS_ALL | VX_PRIVATE_ENV)
#undef  SHELL_STACK_SIZE
#define SHELL_STACK_SIZE 50000
#undef  SHELL_START_AT_BOOT
#define SHELL_START_AT_BOOT TRUE
#undef  SHELL_COMPATIBLE
#define SHELL_COMPATIBLE FALSE
#undef  SHELL_DEFAULT_CONFIG
#define SHELL_DEFAULT_CONFIG ("INTERPRETER=,LINE_EDIT_MODE=,LINE_LENGTH=1024,STRING_FREE=manual,VXE_PATH=.;/bin;/usr/bin;/romfs")
#undef  SHELL_FIRST_CONFIG
#define SHELL_FIRST_CONFIG NULL
#undef  SHELL_REMOTE_CONFIG
#define SHELL_REMOTE_CONFIG NULL
#undef  SHELL_MAX_SESSIONS
#define SHELL_MAX_SESSIONS -1
#undef  SHELL_SPAWNED_TASK_STACK_SIZE
#define SHELL_SPAWNED_TASK_STACK_SIZE 20000
#undef  SHELL_SPAWNED_TASK_PRIORITY
#define SHELL_SPAWNED_TASK_PRIORITY 100
#undef  SHELL_SPAWNED_TASK_OPTIONS
#define SHELL_SPAWNED_TASK_OPTIONS (VX_FP_TASK | VX_STDIO | COPROCS_ALL)
#undef  DEBUG_STACK_TRACE_BUF_SIZE
#define DEBUG_STACK_TRACE_BUF_SIZE 4096
#undef  SHELL_TASK_PRIORITY
#define SHELL_TASK_PRIORITY 1
#undef  SPY_TASKS_MAX
#define SPY_TASKS_MAX 200
#undef  STOP_MODE_AGENT_STACK_SIZE
#define STOP_MODE_AGENT_STACK_SIZE 8192
#undef  STOP_MODE_AGENT_END_DEVICE_NAME
#define STOP_MODE_AGENT_END_DEVICE_NAME NULL
#undef  STOP_MODE_AGENT_END_DEVICE_UNIT
#define STOP_MODE_AGENT_END_DEVICE_UNIT 0
#undef  STOP_MODE_AGENT_END_DEVICE_ADDRESS
#define STOP_MODE_AGENT_END_DEVICE_ADDRESS NULL
#undef  STOP_MODE_AGENT_MTU
#define STOP_MODE_AGENT_MTU 1500
#undef  STOP_MODE_AGENT_END_NUM_MBUFS
#define STOP_MODE_AGENT_END_NUM_MBUFS 5
#undef  STOP_MODE_AGENT_END_NUM_CL_BLKS
#define STOP_MODE_AGENT_END_NUM_CL_BLKS 5
#undef  STOP_MODE_AGENT_END_PORT
#define STOP_MODE_AGENT_END_PORT 0x4321
#undef  STAT_TBL_HASH_SIZE_LOG2
#define STAT_TBL_HASH_SIZE_LOG2 6
#undef  SYM_TBL_HASH_SIZE_LOG2
#define SYM_TBL_HASH_SIZE_LOG2 8
#undef  WV_DEFAULT_BUF_MIN
#define WV_DEFAULT_BUF_MIN 4
#undef  WV_DEFAULT_BUF_MAX
#define WV_DEFAULT_BUF_MAX 16
#undef  WV_DEFAULT_BUF_SIZE
#define WV_DEFAULT_BUF_SIZE 0x8000
#undef  WV_DEFAULT_BUF_THRESH
#define WV_DEFAULT_BUF_THRESH 0x4000
#undef  WV_DEFAULT_BUF_OPTIONS
#define WV_DEFAULT_BUF_OPTIONS 0x0
#undef  WV_MAX_LOGS
#define WV_MAX_LOGS 5
#undef  WV_UPLOAD_STACK_SIZE
#define WV_UPLOAD_STACK_SIZE 8192
#undef  WV_UPLOAD_PRIORITY
#define WV_UPLOAD_PRIORITY 51
#undef  TIP_CONFIG_STRING
#define TIP_CONFIG_STRING ""
#undef  TIP_ESCAPE_CHARACTER
#define TIP_ESCAPE_CHARACTER "~"
#undef  VXDBG_EVT_TASK_PRIORITY
#define VXDBG_EVT_TASK_PRIORITY 25
#undef  VXDBG_EVT_TASK_OPTIONS
#define VXDBG_EVT_TASK_OPTIONS VX_UNBREAKABLE | VX_FP_TASK
#undef  VXDBG_EVT_TASK_STACK_SIZE
#define VXDBG_EVT_TASK_STACK_SIZE 8192
#undef  USER_I_CACHE_MODE
#define USER_I_CACHE_MODE CACHE_WRITETHROUGH
#undef  USER_D_CACHE_MODE
#define USER_D_CACHE_MODE CACHE_COPYBACK
#undef  USER_I_CACHE_ENABLE
#define USER_I_CACHE_ENABLE
#undef  USER_D_CACHE_ENABLE
#define USER_D_CACHE_ENABLE
#undef  APPL_LOG_FD_CFG
#define APPL_LOG_FD_CFG STD_OUT
#undef  APPL_LOG_LEVEL_CFG
#define APPL_LOG_LEVEL_CFG (_LOG_DEC_DFLT | _LOG_LVL_DFLT)
#undef  APPL_KERN_LOG_FD_CFG
#define APPL_KERN_LOG_FD_CFG KERN_LOG_FD
#undef  APPL_KERN_LOG_LEVEL_CFG
#define APPL_KERN_LOG_LEVEL_CFG (_LOG_DEC_DFLT | _LOG_LVL_DFLT)
#undef  VM_PAGE_SIZE
#define VM_PAGE_SIZE 0x10000
#undef  DATA_SEG_ALIGN
#define DATA_SEG_ALIGN 1
#undef  RTP_SHELL_CMD_VERBOSITY
#define RTP_SHELL_CMD_VERBOSITY 1
#undef  RTP_SHELL_CMD_PRIORITY
#define RTP_SHELL_CMD_PRIORITY 220
#undef  RTP_SHELL_CMD_OPTIONS
#define RTP_SHELL_CMD_OPTIONS RTP_GLOBAL_SYMBOLS
#undef  RTP_SHELL_CMD_STACK_SIZE
#define RTP_SHELL_CMD_STACK_SIZE 64 * 1024
#undef  RTP_SHELL_CMD_DELAY
#define RTP_SHELL_CMD_DELAY 0
#undef  RTP_SHELL_CMD_TASK_OPTIONS
#define RTP_SHELL_CMD_TASK_OPTIONS VX_FP_TASK
#undef  NUM_RAWFS_FILES
#define NUM_RAWFS_FILES 10
#undef  NUM_RAWFS_BLOCKS
#define NUM_RAWFS_BLOCKS 256
#undef  VXB_MAX_INTR_VEC
#define VXB_MAX_INTR_VEC 1024
#undef  VXB_MAX_INTR_CHAIN
#define VXB_MAX_INTR_CHAIN 256
#undef  VXB_MAX_INTR_DEFER
#define VXB_MAX_INTR_DEFER 256
#undef  CONSOLE_TTY
#define CONSOLE_TTY 0
#undef  CONSOLE_NAME
#define CONSOLE_NAME "/ttyS0"
#undef  CONSOLE_BAUD_RATE
#define CONSOLE_BAUD_RATE 115200
#undef  IDLE_TASK_EXCEPTION_STACK_SIZE
#define IDLE_TASK_EXCEPTION_STACK_SIZE KERNEL_TASK_EXC_STACK_SIZE
#undef  SYSCLK_TIMER_NAME
#define SYSCLK_TIMER_NAME "vxsimClk"
#undef  SYSCLK_TIMER_NUM
#define SYSCLK_TIMER_NUM 0
#undef  AUXCLK_TIMER_NAME
#define AUXCLK_TIMER_NAME "vxsimAuxClk"
#undef  AUXCLK_TIMER_NUM
#define AUXCLK_TIMER_NUM 0
#undef  TIMESTAMP_TIMER_NAME
#define TIMESTAMP_TIMER_NAME "vxsimTimestamp"
#undef  TIMESTAMP_TIMER_NUM
#define TIMESTAMP_TIMER_NUM 0
#undef  SYS_CLK_RATE
#define SYS_CLK_RATE 50
#undef  SYS_CLK_RATE_MIN
#define SYS_CLK_RATE_MIN 1
#undef  SYS_CLK_RATE_MAX
#define SYS_CLK_RATE_MAX 100
#undef  AUX_CLK_RATE_MIN
#define AUX_CLK_RATE_MIN 1
#undef  AUX_CLK_RATE_MAX
#define AUX_CLK_RATE_MAX (1000)
#undef  ISR_DEFER_MODE
#define ISR_DEFER_MODE ISR_DEFER_MODE_PER_CPU
#undef  ISR_DEFER_TASK_STACK_SIZE
#define ISR_DEFER_TASK_STACK_SIZE 8192
#undef  ISR_DEFER_TASK_PRIO
#define ISR_DEFER_TASK_PRIO 0
#undef  DOSFS_DEFAULT_MAX_FILES
#define DOSFS_DEFAULT_MAX_FILES 20
#undef  DOSFS_DEFAULT_CREATE_OPTIONS
#define DOSFS_DEFAULT_CREATE_OPTIONS 0x04
#undef  DOSFS_COMPAT_NT
#define DOSFS_COMPAT_NT FALSE
#undef  DOSFS_DEFAULT_DATA_DIR_CACHE_SIZE
#define DOSFS_DEFAULT_DATA_DIR_CACHE_SIZE 0x800000
#undef  DOSFS_DEFAULT_FAT_CACHE_SIZE
#define DOSFS_DEFAULT_FAT_CACHE_SIZE 0x100000
#undef  DOSFS_BLOCKS_PER_DATA_DIR_CACHE_GROUP
#define DOSFS_BLOCKS_PER_DATA_DIR_CACHE_GROUP 512
#undef  DOSFS_BLOCKS_PER_FAT_CACHE_GROUP
#define DOSFS_BLOCKS_PER_FAT_CACHE_GROUP 32
#undef  DOSFS_CACHE_BACKGROUND_FLUSH_TASK_ENABLE
#define DOSFS_CACHE_BACKGROUND_FLUSH_TASK_ENABLE FALSE
#undef  DOSFS_DEFAULT_VOL_BIO_BUFFER_SIZE
#define DOSFS_DEFAULT_VOL_BIO_BUFFER_SIZE 32
#undef  ROMFS_MAX_OPEN_FILES
#define ROMFS_MAX_OPEN_FILES NUM_FILES
#undef  ROMFS_DEV_NAME
#define ROMFS_DEV_NAME "/romfs"
#undef  DTB_RELOC_ADDR
#define DTB_RELOC_ADDR (RAM_LOW_ADRS-0x5000)
#undef  DTB_MAX_LEN
#define DTB_MAX_LEN (RAM_LOW_ADRS - STACK_SAVE- DTB_RELOC_ADDR)
#undef  DTS_FILE
#define DTS_FILE vxsim.dts
#undef  VXSIM_KERNEL_SYS_MEM_RGN_BASE
#define VXSIM_KERNEL_SYS_MEM_RGN_BASE 0x180000000LL
#undef  VXSIM_KERNEL_SYS_MEM_RGN_SIZE
#define VXSIM_KERNEL_SYS_MEM_RGN_SIZE 0x80000000LL
#undef  VXSIM_RTP_PRIVATE_RGN_BASE
#define VXSIM_RTP_PRIVATE_RGN_BASE 0x200000000LL
#undef  VXSIM_RTP_PRIVATE_RGN_SIZE
#define VXSIM_RTP_PRIVATE_RGN_SIZE 0x100000000LL
#undef  VXSIM_SHARED_RGN_SIZE
#define VXSIM_SHARED_RGN_SIZE 0x100000000LL
#undef  VXSIM_KERNEL_VIRT_POOL_RGN_SIZE
#define VXSIM_KERNEL_VIRT_POOL_RGN_SIZE 0x100000000LL
#undef  VXSIM_SIMNET_MEM_RGN_SIZE
#define VXSIM_SIMNET_MEM_RGN_SIZE 0x01000000
#undef  NV_RAM_SIZE
#define NV_RAM_SIZE 0x100

#endif /* INCprjParamsh */
